BA10-bsha-1: ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines Class Reference
ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines Class Reference
Inherits ch::zhaw::ba10_bsha_1::strategies::BaseStrategy, and ch::zhaw::ba10_bsha_1::strategies::IMicroGestureDetectionStrategy.
Public Member Functions
void initialize ()
Collection< MicroGesture > detectMicroGestures (Collection< MicroGesture > microGestures)
Protected Member Functions
String getStrategyName ()
String getStrategyDescription ()
Private Member Functions
void setMicroGesture (MicroGesture mg)
double calculateDistance (TouchPoint a, double m1, double q1)
void analyseMicroGestureDirection (MicroGesture mg)
Private Attributes
double tolerance = 130
Detailed Description
Implementation of IMicroGestureDetectionStrategy which detects lines in the given MicroGestures.
Author:
Dominik Giger, Julian Hanhart
Definition at line 17 of file MicroGestureDetectionStrategyLines.java.
Member Function Documentation
void ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.analyseMicroGestureDirection (MicroGesture mg) [private]
Definition at line 210 of file MicroGestureDetectionStrategyLines.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.getPoints(), ch.zhaw.ba10_bsha_1.service.MicroGesture.getType(), ch.zhaw.ba10_bsha_1.service.MicroGesture.setDirection(), and ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.tolerance.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.detectMicroGestures().
double ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.calculateDistance (TouchPoint a, double m1, double q1) [private]
Definition at line 193 of file MicroGestureDetectionStrategyLines.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.setMicroGesture().
Collection<MicroGesture> ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.detectMicroGestures (Collection< MicroGesture > microGestures)
Detect lines in the TouchPoints of the given MicroGestures
Parameters:
micro_gestures
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.IMicroGestureDetectionStrategy.
Definition at line 59 of file MicroGestureDetectionStrategyLines.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.addPoint(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.analyseMicroGestureDirection(), ch.zhaw.ba10_bsha_1.service.MicroGesture.getDirection(), ch.zhaw.ba10_bsha_1.service.MicroGesture.getPoints(), ch.zhaw.ba10_bsha_1.service.MicroGesture.getType(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.setMicroGesture(), and ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.tolerance.
String ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.getStrategyDescription () [protected, virtual]
Return a description of the strategy
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 42 of file MicroGestureDetectionStrategyLines.java.
String ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.getStrategyName () [protected, virtual]
Return the strategy's name
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 37 of file MicroGestureDetectionStrategyLines.java.
void ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.initialize () [virtual]
Initialize the strategy's StrategyArguments
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 34 of file MicroGestureDetectionStrategyLines.java.
void ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.setMicroGesture (MicroGesture mg) [private]
Definition at line 156 of file MicroGestureDetectionStrategyLines.java.
References ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.calculateDistance(), ch.zhaw.ba10_bsha_1.service.MicroGesture.getPoints(), and ch.zhaw.ba10_bsha_1.service.MicroGesture.setType().
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.detectMicroGestures().
Member Data Documentation
double ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.tolerance = 130 [private]
Definition at line 25 of file MicroGestureDetectionStrategyLines.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.analyseMicroGestureDirection(), and ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.detectMicroGestures().
The documentation for this class was generated from the following file:
/media/Daten/Studium/BA/source/BA10-bsha-1/src/ch/zhaw/ba10_bsha_1/strategies/MicroGestureDetectionStrategyLines.java