BA10-bsha-1: ch.zhaw.ba10_bsha_1.graph.Node Class Reference
ch.zhaw.ba10_bsha_1.graph.Node Class Reference
Public Member Functions
Node (int id, String test, char character)
Node (int id)
Node (int id, String test)
Collection< Character > consume (Collection< MicroGesture > micro_gestures, float probability)
int getId ()
void setId (int id)
String getLabel ()
void setLabel (String label)
MicroGestureTester getTester ()
void setTester (MicroGestureTester tester)
char getCharacter ()
void setCharacter (char character)
Collection< Edge > getIncomingEdges ()
void setIncomingEdges (Collection< Edge > incomingEdges)
void addIncomingEdge (Edge edge)
void removeIncomingEdge (Edge edge)
Collection< Edge > getOutgoingEdges ()
void setOutgoingEdges (Collection< Edge > outgoingEdges)
void addOutgoingEdge (Node node, float probability)
void addOutgoingEdge (Edge edge)
void removeOutgoingEdge (Edge edge)
Protected Attributes
int id
String label
MicroGestureTester tester
char character
Collection< Edge > incomingEdges
Collection< Edge > outgoingEdges
Detailed Description
Represents a Node in our graph. May carry a condition to test MicroGestures given to consume as well as a Character it can evaluate MicroGestures to.
Author:
Julian Hanhart, Dominik Giger
Definition at line 19 of file Node.java.
Constructor & Destructor Documentation
ch.zhaw.ba10_bsha_1.graph.Node.Node (int id, String test, char character)
Definition at line 40 of file Node.java.
References ch.zhaw.ba10_bsha_1.graph.Node.incomingEdges, ch.zhaw.ba10_bsha_1.graph.Node.label, ch.zhaw.ba10_bsha_1.graph.Node.outgoingEdges, and ch.zhaw.ba10_bsha_1.graph.Node.tester.
ch.zhaw.ba10_bsha_1.graph.Node.Node (int id)
Definition at line 49 of file Node.java.
ch.zhaw.ba10_bsha_1.graph.Node.Node (int id, String test)
Definition at line 53 of file Node.java.
Member Function Documentation
void ch.zhaw.ba10_bsha_1.graph.Node.addIncomingEdge (Edge edge)
Definition at line 148 of file Node.java.
References ch.zhaw.ba10_bsha_1.graph.Node.incomingEdges.
Referenced by ch.zhaw.ba10_bsha_1.graph.GraphMLParser.endDocument().
void ch.zhaw.ba10_bsha_1.graph.Node.addOutgoingEdge (Edge edge)
Definition at line 170 of file Node.java.
References ch.zhaw.ba10_bsha_1.graph.Node.outgoingEdges.
void ch.zhaw.ba10_bsha_1.graph.Node.addOutgoingEdge (Node node, float probability)
Definition at line 165 of file Node.java.
References ch.zhaw.ba10_bsha_1.graph.Node.outgoingEdges.
Referenced by ch.zhaw.ba10_bsha_1.graph.GraphMLPullParser.buildGraph(), ch.zhaw.ba10_bsha_1.graph.GraphFactoryDummy.createRoot(), and ch.zhaw.ba10_bsha_1.graph.GraphMLParser.endDocument().
Collection<Character> ch.zhaw.ba10_bsha_1.graph.Node.consume (Collection< MicroGesture > micro_gestures, float probability)
Feed MicroGestures to Node and return recognized Characters (recursively)
Parameters:
micro_gestures
probability
Definition at line 69 of file Node.java.
References ch.zhaw.ba10_bsha_1.graph.Node.character, ch.zhaw.ba10_bsha_1.graph.Node.outgoingEdges, ch.zhaw.ba10_bsha_1.graph.Node.tester, and ch.zhaw.ba10_bsha_1.service.MicroGestureTester.validate().
Referenced by ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyGraph.detectCharacter(), and ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyDummyGraph.detectCharacter().
char ch.zhaw.ba10_bsha_1.graph.Node.getCharacter ()
Definition at line 131 of file Node.java.
References ch.zhaw.ba10_bsha_1.graph.Node.character.
int ch.zhaw.ba10_bsha_1.graph.Node.getId ()
Definition at line 104 of file Node.java.
References ch.zhaw.ba10_bsha_1.graph.Node.id.
Referenced by ch.zhaw.ba10_bsha_1.graph.GraphMLPullParser.endTag().
Collection<Edge> ch.zhaw.ba10_bsha_1.graph.Node.getIncomingEdges ()
Definition at line 140 of file Node.java.
References ch.zhaw.ba10_bsha_1.graph.Node.incomingEdges.
String ch.zhaw.ba10_bsha_1.graph.Node.getLabel ()
Definition at line 113 of file Node.java.
References ch.zhaw.ba10_bsha_1.graph.Node.label.
Collection<Edge> ch.zhaw.ba10_bsha_1.graph.Node.getOutgoingEdges ()
Definition at line 157 of file Node.java.
References ch.zhaw.ba10_bsha_1.graph.Node.outgoingEdges.
MicroGestureTester ch.zhaw.ba10_bsha_1.graph.Node.getTester ()
Definition at line 122 of file Node.java.
References ch.zhaw.ba10_bsha_1.graph.Node.tester.
void ch.zhaw.ba10_bsha_1.graph.Node.removeIncomingEdge (Edge edge)
Definition at line 152 of file Node.java.
References ch.zhaw.ba10_bsha_1.graph.Node.incomingEdges.
void ch.zhaw.ba10_bsha_1.graph.Node.removeOutgoingEdge (Edge edge)
Definition at line 174 of file Node.java.
References ch.zhaw.ba10_bsha_1.graph.Node.outgoingEdges.
void ch.zhaw.ba10_bsha_1.graph.Node.setCharacter (char character)
Definition at line 135 of file Node.java.
Referenced by ch.zhaw.ba10_bsha_1.graph.GraphMLPullParser.handleText().
void ch.zhaw.ba10_bsha_1.graph.Node.setId (int id)
Definition at line 108 of file Node.java.
void ch.zhaw.ba10_bsha_1.graph.Node.setIncomingEdges (Collection< Edge > incomingEdges)
Definition at line 144 of file Node.java.
void ch.zhaw.ba10_bsha_1.graph.Node.setLabel (String label)
Definition at line 117 of file Node.java.
void ch.zhaw.ba10_bsha_1.graph.Node.setOutgoingEdges (Collection< Edge > outgoingEdges)
Definition at line 161 of file Node.java.
void ch.zhaw.ba10_bsha_1.graph.Node.setTester (MicroGestureTester tester)
Definition at line 126 of file Node.java.
Referenced by ch.zhaw.ba10_bsha_1.graph.GraphMLPullParser.handleText().
Member Data Documentation
char ch.zhaw.ba10_bsha_1.graph.Node.character [protected]
Definition at line 30 of file Node.java.
Referenced by ch.zhaw.ba10_bsha_1.graph.Node.consume(), and ch.zhaw.ba10_bsha_1.graph.Node.getCharacter().
int ch.zhaw.ba10_bsha_1.graph.Node.id [protected]
Definition at line 27 of file Node.java.
Referenced by ch.zhaw.ba10_bsha_1.graph.Node.getId().
Collection<Edge> ch.zhaw.ba10_bsha_1.graph.Node.incomingEdges [protected]
Definition at line 31 of file Node.java.
Referenced by ch.zhaw.ba10_bsha_1.graph.Node.addIncomingEdge(), ch.zhaw.ba10_bsha_1.graph.Node.getIncomingEdges(), ch.zhaw.ba10_bsha_1.graph.Node.Node(), and ch.zhaw.ba10_bsha_1.graph.Node.removeIncomingEdge().
String ch.zhaw.ba10_bsha_1.graph.Node.label [protected]
Definition at line 28 of file Node.java.
Referenced by ch.zhaw.ba10_bsha_1.graph.Node.getLabel(), and ch.zhaw.ba10_bsha_1.graph.Node.Node().
Collection<Edge> ch.zhaw.ba10_bsha_1.graph.Node.outgoingEdges [protected]
Definition at line 32 of file Node.java.
Referenced by ch.zhaw.ba10_bsha_1.graph.Node.addOutgoingEdge(), ch.zhaw.ba10_bsha_1.graph.Node.consume(), ch.zhaw.ba10_bsha_1.graph.Node.getOutgoingEdges(), ch.zhaw.ba10_bsha_1.graph.Node.Node(), and ch.zhaw.ba10_bsha_1.graph.Node.removeOutgoingEdge().
MicroGestureTester ch.zhaw.ba10_bsha_1.graph.Node.tester [protected]
Definition at line 29 of file Node.java.
Referenced by ch.zhaw.ba10_bsha_1.graph.Node.consume(), ch.zhaw.ba10_bsha_1.graph.Node.getTester(), and ch.zhaw.ba10_bsha_1.graph.Node.Node().
The documentation for this class was generated from the following file:
/media/Daten/Studium/BA/source/BA10-bsha-1/src/ch/zhaw/ba10_bsha_1/graph/Node.java