BA10-bsha-1: ch.zhaw.ba10_bsha_1.ime.PadView Class Reference
ch.zhaw.ba10_bsha_1.ime.PadView Class Reference
Inherits android::inputmethodservice::KeyboardView, and ch::zhaw::ba10_bsha_1::ime::IObservable.
Public Member Functions
PadView (Context context, AttributeSet attrs)
PadView (Context context, AttributeSet attrs, int defStyle)
void onSizeChanged (int w, int h, int oldw, int oldh)
void onDraw (Canvas canvas)
boolean onTouchEvent (MotionEvent event)
void attachObserver (IObserver observer)
void detachObserver (IObserver observer)
void notifyObservers ()
void notifyObservers (int event_type)
int getEventType ()
void closing ()
void clear ()
Collection< TouchPoint > getLastPoints ()
Static Public Attributes
static final int EVENT_TYPE_NONE = 0
static final int EVENT_TYPE_NEW_POINTS = 1
static final int EVENT_TYPE_TOUCH_UP = 2
static final int EVENT_TYPE_SPACE = 3
static final int EVENT_TYPE_BACKSPACE = 4
Private Member Functions
void init ()
void paintBaseLines (Canvas canvas)
void touchStart (float x, float y, float pressure)
void touchMove (float x, float y, float pressure)
void touchUp ()
Private Attributes
ArrayList< TouchInput > inputs
TouchInput currentInput
int oldPathColor
int curPathColor
float lastX
float lastY
float fieldHeight
Bitmap bitmap
Paint bmPaint
Paint paint
float margin
ArrayList< IObserver > observers
int eventType
Static Private Attributes
static final float TOUCH_TOLERANCE = 4
Detailed Description
Implementation of a KeyboardView to gather data for the DetectionService.
Notifies its IObservers on input events such as new TouchInputs, crossing out of existing TouchInputs (seen as a backspace) or starting of new TouchInputs with a certain offset (seen as a space).
Definition at line 24 of file PadView.java.
Constructor & Destructor Documentation
ch.zhaw.ba10_bsha_1.ime.PadView.PadView (Context context, AttributeSet attrs)
Definition at line 63 of file PadView.java.
References ch.zhaw.ba10_bsha_1.ime.PadView.init().
ch.zhaw.ba10_bsha_1.ime.PadView.PadView (Context context, AttributeSet attrs, int defStyle)
Definition at line 68 of file PadView.java.
References ch.zhaw.ba10_bsha_1.ime.PadView.init().
Member Function Documentation
void ch.zhaw.ba10_bsha_1.ime.PadView.attachObserver (IObserver observer)
Attach an IObserver to the IObservable
Implements ch.zhaw.ba10_bsha_1.ime.IObservable.
Definition at line 263 of file PadView.java.
References ch.zhaw.ba10_bsha_1.ime.PadView.observers.
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onInitializeInterface().
void ch.zhaw.ba10_bsha_1.ime.PadView.clear ()
Removes all TouchInputs and marks View as invalid
Definition at line 315 of file PadView.java.
References ch.zhaw.ba10_bsha_1.ime.PadView.inputs.
Referenced by ch.zhaw.ba10_bsha_1.ime.PadView.closing().
void ch.zhaw.ba10_bsha_1.ime.PadView.closing ()
Definition at line 307 of file PadView.java.
References ch.zhaw.ba10_bsha_1.ime.PadView.clear().
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.handleClose(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onFinishInput(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onStartInputView().
void ch.zhaw.ba10_bsha_1.ime.PadView.detachObserver (IObserver observer)
Detach an IObserver from the IObservable
Implements ch.zhaw.ba10_bsha_1.ime.IObservable.
Definition at line 271 of file PadView.java.
References ch.zhaw.ba10_bsha_1.ime.PadView.observers.
int ch.zhaw.ba10_bsha_1.ime.PadView.getEventType ()
Definition at line 296 of file PadView.java.
References ch.zhaw.ba10_bsha_1.ime.PadView.eventType.
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.update().
Collection<TouchPoint> ch.zhaw.ba10_bsha_1.ime.PadView.getLastPoints ()
Returns the points gathered the last
Returns:
Collection<TouchPoint>
Definition at line 325 of file PadView.java.
References ch.zhaw.ba10_bsha_1.ime.TouchInput.getPoints(), and ch.zhaw.ba10_bsha_1.ime.PadView.inputs.
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.update().
void ch.zhaw.ba10_bsha_1.ime.PadView.init () [private]
Initialize the classes attributes
Definition at line 76 of file PadView.java.
References ch.zhaw.ba10_bsha_1.ime.PadView.bitmap, ch.zhaw.ba10_bsha_1.ime.PadView.bmPaint, ch.zhaw.ba10_bsha_1.ime.PadView.curPathColor, ch.zhaw.ba10_bsha_1.ime.PadView.currentInput, ch.zhaw.ba10_bsha_1.ime.PadView.EVENT_TYPE_NONE, ch.zhaw.ba10_bsha_1.ime.PadView.eventType, ch.zhaw.ba10_bsha_1.ime.PadView.inputs, ch.zhaw.ba10_bsha_1.ime.PadView.margin, ch.zhaw.ba10_bsha_1.ime.PadView.observers, ch.zhaw.ba10_bsha_1.ime.PadView.oldPathColor, and ch.zhaw.ba10_bsha_1.ime.PadView.paint.
Referenced by ch.zhaw.ba10_bsha_1.ime.PadView.PadView().
void ch.zhaw.ba10_bsha_1.ime.PadView.notifyObservers (int event_type)
Notify all attached IObservers of changes, setting the event type while doing so
Parameters:
event_type
Definition at line 290 of file PadView.java.
References ch.zhaw.ba10_bsha_1.ime.PadView.EVENT_TYPE_NONE, ch.zhaw.ba10_bsha_1.ime.PadView.eventType, and ch.zhaw.ba10_bsha_1.ime.PadView.notifyObservers().
void ch.zhaw.ba10_bsha_1.ime.PadView.notifyObservers ()
Notify all attached IObservers of changes
Implements ch.zhaw.ba10_bsha_1.ime.IObservable.
Definition at line 279 of file PadView.java.
References ch.zhaw.ba10_bsha_1.ime.PadView.observers.
Referenced by ch.zhaw.ba10_bsha_1.ime.PadView.notifyObservers(), ch.zhaw.ba10_bsha_1.ime.PadView.touchStart(), and ch.zhaw.ba10_bsha_1.ime.PadView.touchUp().
void ch.zhaw.ba10_bsha_1.ime.PadView.onDraw (Canvas canvas)
Draw the View's background and the existing TouchInputs as well as the currently active TouchInput
Definition at line 117 of file PadView.java.
References ch.zhaw.ba10_bsha_1.ime.PadView.bitmap, ch.zhaw.ba10_bsha_1.ime.PadView.bmPaint, ch.zhaw.ba10_bsha_1.ime.PadView.curPathColor, ch.zhaw.ba10_bsha_1.ime.PadView.currentInput, ch.zhaw.ba10_bsha_1.ime.TouchInput.getPath(), ch.zhaw.ba10_bsha_1.ime.PadView.inputs, ch.zhaw.ba10_bsha_1.ime.PadView.oldPathColor, ch.zhaw.ba10_bsha_1.ime.PadView.paint, and ch.zhaw.ba10_bsha_1.ime.PadView.paintBaseLines().
void ch.zhaw.ba10_bsha_1.ime.PadView.onSizeChanged (int w, int h, int oldw, int oldh)
Definition at line 104 of file PadView.java.
References ch.zhaw.ba10_bsha_1.ime.PadView.bitmap, ch.zhaw.ba10_bsha_1.ime.PadView.fieldHeight, and ch.zhaw.ba10_bsha_1.ime.PadView.margin.
boolean ch.zhaw.ba10_bsha_1.ime.PadView.onTouchEvent (MotionEvent event)
Handle touchscreen events
Definition at line 169 of file PadView.java.
References ch.zhaw.ba10_bsha_1.ime.PadView.touchMove(), ch.zhaw.ba10_bsha_1.ime.PadView.touchStart(), and ch.zhaw.ba10_bsha_1.ime.PadView.touchUp().
void ch.zhaw.ba10_bsha_1.ime.PadView.paintBaseLines (Canvas canvas) [private]
Draw the View's base lines on the background
Parameters:
canvas
Definition at line 136 of file PadView.java.
References ch.zhaw.ba10_bsha_1.ime.PadView.fieldHeight, and ch.zhaw.ba10_bsha_1.ime.PadView.margin.
Referenced by ch.zhaw.ba10_bsha_1.ime.PadView.onDraw().
void ch.zhaw.ba10_bsha_1.ime.PadView.touchMove (float x, float y, float pressure) [private]
React on movement with the finger on the touchscreen
Parameters:
x
y
pressure
Definition at line 220 of file PadView.java.
References ch.zhaw.ba10_bsha_1.ime.TouchInput.add(), ch.zhaw.ba10_bsha_1.ime.PadView.currentInput, ch.zhaw.ba10_bsha_1.ime.PadView.lastX, ch.zhaw.ba10_bsha_1.ime.PadView.lastY, and ch.zhaw.ba10_bsha_1.ime.PadView.TOUCH_TOLERANCE.
Referenced by ch.zhaw.ba10_bsha_1.ime.PadView.onTouchEvent().
void ch.zhaw.ba10_bsha_1.ime.PadView.touchStart (float x, float y, float pressure) [private]
React on a newly started touchscreen input by creating a new TouchInput
Parameters:
x
y
pressure
Definition at line 197 of file PadView.java.
References ch.zhaw.ba10_bsha_1.ime.TouchInput.add(), ch.zhaw.ba10_bsha_1.ime.PadView.currentInput, ch.zhaw.ba10_bsha_1.ime.PadView.EVENT_TYPE_SPACE, ch.zhaw.ba10_bsha_1.ime.PadView.inputs, ch.zhaw.ba10_bsha_1.ime.PadView.lastX, ch.zhaw.ba10_bsha_1.ime.PadView.lastY, and ch.zhaw.ba10_bsha_1.ime.PadView.notifyObservers().
Referenced by ch.zhaw.ba10_bsha_1.ime.PadView.onTouchEvent().
void ch.zhaw.ba10_bsha_1.ime.PadView.touchUp () [private]
React on the ending of a touchscreen input
Definition at line 233 of file PadView.java.
References ch.zhaw.ba10_bsha_1.ime.TouchInput.crosses(), ch.zhaw.ba10_bsha_1.ime.PadView.currentInput, ch.zhaw.ba10_bsha_1.ime.PadView.EVENT_TYPE_BACKSPACE, ch.zhaw.ba10_bsha_1.ime.PadView.EVENT_TYPE_TOUCH_UP, ch.zhaw.ba10_bsha_1.ime.PadView.inputs, and ch.zhaw.ba10_bsha_1.ime.PadView.notifyObservers().
Referenced by ch.zhaw.ba10_bsha_1.ime.PadView.onTouchEvent().
Member Data Documentation
Bitmap ch.zhaw.ba10_bsha_1.ime.PadView.bitmap [private]
Definition at line 49 of file PadView.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.PadView.init(), ch.zhaw.ba10_bsha_1.ime.PadView.onDraw(), and ch.zhaw.ba10_bsha_1.ime.PadView.onSizeChanged().
Paint ch.zhaw.ba10_bsha_1.ime.PadView.bmPaint [private]
Definition at line 50 of file PadView.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.PadView.init(), and ch.zhaw.ba10_bsha_1.ime.PadView.onDraw().
int ch.zhaw.ba10_bsha_1.ime.PadView.curPathColor [private]
Definition at line 43 of file PadView.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.PadView.init(), and ch.zhaw.ba10_bsha_1.ime.PadView.onDraw().
TouchInput ch.zhaw.ba10_bsha_1.ime.PadView.currentInput [private]
Definition at line 41 of file PadView.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.PadView.init(), ch.zhaw.ba10_bsha_1.ime.PadView.onDraw(), ch.zhaw.ba10_bsha_1.ime.PadView.touchMove(), ch.zhaw.ba10_bsha_1.ime.PadView.touchStart(), and ch.zhaw.ba10_bsha_1.ime.PadView.touchUp().
final int ch.zhaw.ba10_bsha_1.ime.PadView.EVENT_TYPE_BACKSPACE = 4 [static]
Definition at line 36 of file PadView.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.PadView.touchUp().
final int ch.zhaw.ba10_bsha_1.ime.PadView.EVENT_TYPE_NEW_POINTS = 1 [static]
Definition at line 33 of file PadView.java.
final int ch.zhaw.ba10_bsha_1.ime.PadView.EVENT_TYPE_NONE = 0 [static]
Definition at line 32 of file PadView.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.PadView.init(), and ch.zhaw.ba10_bsha_1.ime.PadView.notifyObservers().
final int ch.zhaw.ba10_bsha_1.ime.PadView.EVENT_TYPE_SPACE = 3 [static]
Definition at line 35 of file PadView.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.PadView.touchStart().
final int ch.zhaw.ba10_bsha_1.ime.PadView.EVENT_TYPE_TOUCH_UP = 2 [static]
Definition at line 34 of file PadView.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.PadView.touchUp().
int ch.zhaw.ba10_bsha_1.ime.PadView.eventType [private]
Definition at line 55 of file PadView.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.PadView.getEventType(), ch.zhaw.ba10_bsha_1.ime.PadView.init(), and ch.zhaw.ba10_bsha_1.ime.PadView.notifyObservers().
float ch.zhaw.ba10_bsha_1.ime.PadView.fieldHeight [private]
Definition at line 47 of file PadView.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.PadView.onSizeChanged(), and ch.zhaw.ba10_bsha_1.ime.PadView.paintBaseLines().
ArrayList<TouchInput> ch.zhaw.ba10_bsha_1.ime.PadView.inputs [private]
Definition at line 40 of file PadView.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.PadView.clear(), ch.zhaw.ba10_bsha_1.ime.PadView.getLastPoints(), ch.zhaw.ba10_bsha_1.ime.PadView.init(), ch.zhaw.ba10_bsha_1.ime.PadView.onDraw(), ch.zhaw.ba10_bsha_1.ime.PadView.touchStart(), and ch.zhaw.ba10_bsha_1.ime.PadView.touchUp().
float ch.zhaw.ba10_bsha_1.ime.PadView.lastX [private]
Definition at line 45 of file PadView.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.PadView.touchMove(), and ch.zhaw.ba10_bsha_1.ime.PadView.touchStart().
float ch.zhaw.ba10_bsha_1.ime.PadView.lastY [private]
Definition at line 46 of file PadView.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.PadView.touchMove(), and ch.zhaw.ba10_bsha_1.ime.PadView.touchStart().
float ch.zhaw.ba10_bsha_1.ime.PadView.margin [private]
Definition at line 52 of file PadView.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.PadView.init(), ch.zhaw.ba10_bsha_1.ime.PadView.onSizeChanged(), and ch.zhaw.ba10_bsha_1.ime.PadView.paintBaseLines().
ArrayList<IObserver> ch.zhaw.ba10_bsha_1.ime.PadView.observers [private]
Definition at line 54 of file PadView.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.PadView.attachObserver(), ch.zhaw.ba10_bsha_1.ime.PadView.detachObserver(), ch.zhaw.ba10_bsha_1.ime.PadView.init(), and ch.zhaw.ba10_bsha_1.ime.PadView.notifyObservers().
int ch.zhaw.ba10_bsha_1.ime.PadView.oldPathColor [private]
Definition at line 42 of file PadView.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.PadView.init(), and ch.zhaw.ba10_bsha_1.ime.PadView.onDraw().
Paint ch.zhaw.ba10_bsha_1.ime.PadView.paint [private]
Definition at line 51 of file PadView.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.PadView.init(), and ch.zhaw.ba10_bsha_1.ime.PadView.onDraw().
final float ch.zhaw.ba10_bsha_1.ime.PadView.TOUCH_TOLERANCE = 4 [static, private]
Definition at line 38 of file PadView.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.PadView.touchMove().
The documentation for this class was generated from the following file:
/media/Daten/Studium/BA/source/BA10-bsha-1/src/ch/zhaw/ba10_bsha_1/ime/PadView.java