BA10-bsha-1: ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog Class Reference
ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog Class Reference
Inherits ch::zhaw::ba10_bsha_1::strategies::BaseStrategy, and ch::zhaw::ba10_bsha_1::strategies::IPreprocessingStrategy.
Public Member Functions
void initialize ()
MicroGesture process (MicroGesture micro_gesture)
Protected Member Functions
String getStrategyName ()
String getStrategyDescription ()
Private Attributes
File logFile
Static Private Attributes
static final String TAG = "PPS_Log"
Detailed Description
Example of an implementation of IPreprocessingStrategy which logs the given TouchPoints to Logcat and into a log-file and returns them unchanged
Author:
Julian Hanhart, Dominik Giger
Definition at line 25 of file PreprocessingStrategyLog.java.
Member Function Documentation
String ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog.getStrategyDescription () [protected, virtual]
Return a description of the strategy
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 63 of file PreprocessingStrategyLog.java.
String ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog.getStrategyName () [protected, virtual]
Return the strategy's name
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 58 of file PreprocessingStrategyLog.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog.initialize().
void ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog.initialize () [virtual]
Initialize the strategy's StrategyArguments
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 43 of file PreprocessingStrategyLog.java.
References ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.addArgument(), ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.getArgument(), ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog.getStrategyName(), ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.hasArgument(), ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog.logFile, and ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog.TAG.
MicroGesture ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog.process (MicroGesture micro_gesture)
Logs the TouchPoints of the given MicroGesture to Logcat and into a file and returns the unchanged
Parameters:
micro_gesture
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.IPreprocessingStrategy.
Definition at line 81 of file PreprocessingStrategyLog.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.getPoints(), ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog.logFile, ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog.TAG, and ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.toString().
Member Data Documentation
File ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog.logFile [private]
Definition at line 34 of file PreprocessingStrategyLog.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog.initialize(), and ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog.process().
final String ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog.TAG = "PPS_Log" [static, private]
Definition at line 33 of file PreprocessingStrategyLog.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog.initialize(), and ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog.process().
The documentation for this class was generated from the following file:
/media/Daten/Studium/BA/source/BA10-bsha-1/src/ch/zhaw/ba10_bsha_1/strategies/PreprocessingStrategyLog.java