BA10-bsha-1: ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature Class Reference
ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature Class Reference
Inherits ch::zhaw::ba10_bsha_1::strategies::BaseStrategy, and ch::zhaw::ba10_bsha_1::strategies::IMicroGestureDetectionStrategy.
Public Member Functions
void initialize ()
Collection< MicroGesture > detectMicroGestures (Collection< MicroGesture > micro_gestures)
Protected Member Functions
String getStrategyName ()
String getStrategyDescription ()
Private Member Functions
void setMicroGesture (MicroGesture mg)
double calculateDistance (TouchPoint a, double m1, double q1)
int analyseMicroGestureDirection (MicroGesture mg)
boolean directionIsUp (double direction)
boolean directionIsDown (double direction)
boolean directionIsRight (double direction)
boolean directionIsLeft (double direction)
Detailed Description
Implementation of IMicroGestureDetectionStrategy that recognizes MicroGestures by changes in curvature.
Author:
Dominik Giger, Julian Hanhart
Definition at line 19 of file MicroGestureDetectionStrategyCurvature.java.
Member Function Documentation
int ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.analyseMicroGestureDirection (MicroGesture mg) [private]
Definition at line 220 of file MicroGestureDetectionStrategyCurvature.java.
References ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.directionIsDown(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.directionIsLeft(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.directionIsRight(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.directionIsUp(), and ch.zhaw.ba10_bsha_1.service.MicroGesture.getPoints().
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.detectMicroGestures().
double ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.calculateDistance (TouchPoint a, double m1, double q1) [private]
Definition at line 203 of file MicroGestureDetectionStrategyCurvature.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.setMicroGesture().
Collection<MicroGesture> ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.detectMicroGestures (Collection< MicroGesture > micro_gestures)
Detect MicroGestures in the TouchPoints of the given MicroGestures
Parameters:
micro_gestures
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.IMicroGestureDetectionStrategy.
Definition at line 53 of file MicroGestureDetectionStrategyCurvature.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.addPoint(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.analyseMicroGestureDirection(), ch.zhaw.ba10_bsha_1.service.MicroGesture.getPoints(), ch.zhaw.ba10_bsha_1.service.MicroGesture.setDirection(), and ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.setMicroGesture().
boolean ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.directionIsDown (double direction) [private]
Definition at line 253 of file MicroGestureDetectionStrategyCurvature.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.analyseMicroGestureDirection().
boolean ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.directionIsLeft (double direction) [private]
Definition at line 263 of file MicroGestureDetectionStrategyCurvature.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.analyseMicroGestureDirection().
boolean ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.directionIsRight (double direction) [private]
Definition at line 258 of file MicroGestureDetectionStrategyCurvature.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.analyseMicroGestureDirection().
boolean ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.directionIsUp (double direction) [private]
Definition at line 248 of file MicroGestureDetectionStrategyCurvature.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.analyseMicroGestureDirection().
String ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.getStrategyDescription () [protected, virtual]
Return a description of the strategy
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 36 of file MicroGestureDetectionStrategyCurvature.java.
String ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.getStrategyName () [protected, virtual]
Return the strategy's name
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 31 of file MicroGestureDetectionStrategyCurvature.java.
void ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.initialize () [virtual]
Initialize the strategy's StrategyArguments
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 28 of file MicroGestureDetectionStrategyCurvature.java.
void ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.setMicroGesture (MicroGesture mg) [private]
Definition at line 161 of file MicroGestureDetectionStrategyCurvature.java.
References ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.calculateDistance(), ch.zhaw.ba10_bsha_1.service.MicroGesture.getPoints(), and ch.zhaw.ba10_bsha_1.service.MicroGesture.setType().
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.detectMicroGestures().
The documentation for this class was generated from the following file:
/media/Daten/Studium/BA/source/BA10-bsha-1/src/ch/zhaw/ba10_bsha_1/strategies/MicroGestureDetectionStrategyCurvature.java