BA10-bsha-1: ch.zhaw.ba10_bsha_1.service.DetectionService Class Reference
ch.zhaw.ba10_bsha_1.service.DetectionService Class Reference
Inherits android::app::Service.
Public Member Functions
void onCreate ()
void onDestroy ()
IBinder onBind (Intent intent)
Static Public Member Functions
static Context getContext ()
Package Attributes
final RemoteCallbackList
< IReturnResults > callbacks = new RemoteCallbackList<IReturnResults>()
Private Member Functions
void initDetection ()
Collection< Character > startDetection ()
void showNotification ()
Static Private Member Functions
static String printStrategy (IStrategy strategy, int type)
static StrategyManager< IStrategy > getManagerByType (int type)
Private Attributes
final int BUFFER_SIZE = 10
final boolean DEBUG = true
ArrayList< TouchPoint > inputPoints
RingBuffer< TouchPoint > buffer
StrategyQueue
< IPreprocessingStrategy > preprocessingSteps
StrategyQueue
< IMicroGestureDetectionStrategy > mgDetectionSteps
ICharacterDetectionStrategy charDetectionStrategy
IPostprocessingStrategy postprocessingStrategy
NotificationManager notificationManager
final IDetectionService.Stub serviceBinder
Static Private Attributes
static final int STRATEGY_TYPE_PREPROCESSING = 0
static final int STRATEGY_TYPE_MICROGESTURE_DETECTION = 1
static final int STRATEGY_TYPE_CHARACTER_DETECTION = 2
static final int STRATEGY_TYPE_POSTPROCESSING = 3
static final String TAG = "DetectionService"
static Context CONTEXT
Detailed Description
Implementation of the remote Service used for the detection of Characters out of a list of input points.
Based on the RemoteService code sample from the API Demos example of the Android SDK.
Author:
Julian Hanhart, Dominik Giger
Definition at line 49 of file DetectionService.java.
Member Function Documentation
static Context ch.zhaw.ba10_bsha_1.service.DetectionService.getContext () [static]
Get the Application's Context
Returns:
Definition at line 467 of file DetectionService.java.
References ch.zhaw.ba10_bsha_1.service.DetectionService.CONTEXT.
static StrategyManager<IStrategy> ch.zhaw.ba10_bsha_1.service.DetectionService.getManagerByType (int type) [static, private]
Get the corresponding StrategyManager to the given Manager-Type
Parameters:
type
Returns:
Definition at line 435 of file DetectionService.java.
References ch.zhaw.ba10_bsha_1.service.DetectionService.STRATEGY_TYPE_CHARACTER_DETECTION, ch.zhaw.ba10_bsha_1.service.DetectionService.STRATEGY_TYPE_MICROGESTURE_DETECTION, ch.zhaw.ba10_bsha_1.service.DetectionService.STRATEGY_TYPE_POSTPROCESSING, and ch.zhaw.ba10_bsha_1.service.DetectionService.STRATEGY_TYPE_PREPROCESSING.
void ch.zhaw.ba10_bsha_1.service.DetectionService.initDetection () [private]
Initialisation of the detection. This is the place where one can define, which strategies should be used on the input and in what order they should be applied
Definition at line 94 of file DetectionService.java.
References ch.zhaw.ba10_bsha_1.service.DetectionService.buffer, ch.zhaw.ba10_bsha_1.service.DetectionService.BUFFER_SIZE, ch.zhaw.ba10_bsha_1.service.DetectionService.charDetectionStrategy, ch.zhaw.ba10_bsha_1.service.DetectionService.inputPoints, ch.zhaw.ba10_bsha_1.service.DetectionService.mgDetectionSteps, ch.zhaw.ba10_bsha_1.service.DetectionService.postprocessingStrategy, and ch.zhaw.ba10_bsha_1.service.DetectionService.preprocessingSteps.
Referenced by ch.zhaw.ba10_bsha_1.service.DetectionService.onCreate().
IBinder ch.zhaw.ba10_bsha_1.service.DetectionService.onBind (Intent intent)
Called when Service is bound to
Definition at line 240 of file DetectionService.java.
References ch.zhaw.ba10_bsha_1.service.DetectionService.serviceBinder.
void ch.zhaw.ba10_bsha_1.service.DetectionService.onCreate ()
Called when the Service is created
Definition at line 211 of file DetectionService.java.
References ch.zhaw.ba10_bsha_1.service.DetectionService.CONTEXT, ch.zhaw.ba10_bsha_1.service.DetectionService.initDetection(), ch.zhaw.ba10_bsha_1.service.DetectionService.notificationManager, and ch.zhaw.ba10_bsha_1.service.DetectionService.showNotification().
void ch.zhaw.ba10_bsha_1.service.DetectionService.onDestroy ()
Called when the Service is destroyed
Definition at line 225 of file DetectionService.java.
References ch.zhaw.ba10_bsha_1.service.DetectionService.callbacks, and ch.zhaw.ba10_bsha_1.service.DetectionService.notificationManager.
static String ch.zhaw.ba10_bsha_1.service.DetectionService.printStrategy (IStrategy strategy, int type) [static, private]
Get String-representation of the given IStrategy to be send over the AIDL-interface
Parameters:
strategy
type
Returns:
Definition at line 416 of file DetectionService.java.
References ch.zhaw.ba10_bsha_1.strategies.IStrategy.getDescription(), ch.zhaw.ba10_bsha_1.strategies.IStrategy.isEnabled(), and ch.zhaw.ba10_bsha_1.strategies.IStrategy.toString().
void ch.zhaw.ba10_bsha_1.service.DetectionService.showNotification () [private]
Show a Notification while this Service is running.
Definition at line 474 of file DetectionService.java.
References ch.zhaw.ba10_bsha_1.service.DetectionService.notificationManager.
Referenced by ch.zhaw.ba10_bsha_1.service.DetectionService.onCreate().
Collection<Character> ch.zhaw.ba10_bsha_1.service.DetectionService.startDetection () [private]
Starts the detection of Characters from the input points (the buffer is first emptied)
Definition at line 124 of file DetectionService.java.
References ch.zhaw.ba10_bsha_1.service.DetectionService.buffer, ch.zhaw.ba10_bsha_1.service.DetectionService.callbacks, ch.zhaw.ba10_bsha_1.service.DetectionService.charDetectionStrategy, ch.zhaw.ba10_bsha_1.service.DetectionService.DEBUG, ch.zhaw.ba10_bsha_1.strategies.ICharacterDetectionStrategy.detectCharacter(), ch.zhaw.ba10_bsha_1.strategies.IMicroGestureDetectionStrategy.detectMicroGestures(), ch.zhaw.ba10_bsha_1.service.DetectionService.inputPoints, ch.zhaw.ba10_bsha_1.strategies.IStrategy.isEnabled(), ch.zhaw.ba10_bsha_1.service.DetectionService.mgDetectionSteps, ch.zhaw.ba10_bsha_1.service.DetectionService.postprocessingStrategy, ch.zhaw.ba10_bsha_1.service.DetectionService.preprocessingSteps, ch.zhaw.ba10_bsha_1.strategies.IPostprocessingStrategy.process(), ch.zhaw.ba10_bsha_1.strategies.IPreprocessingStrategy.process(), and ch.zhaw.ba10_bsha_1.service.DetectionService.TAG.
Member Data Documentation
RingBuffer<TouchPoint> ch.zhaw.ba10_bsha_1.service.DetectionService.buffer [private]
Definition at line 75 of file DetectionService.java.
Referenced by ch.zhaw.ba10_bsha_1.service.DetectionService.initDetection(), and ch.zhaw.ba10_bsha_1.service.DetectionService.startDetection().
final int ch.zhaw.ba10_bsha_1.service.DetectionService.BUFFER_SIZE = 10 [private]
Definition at line 71 of file DetectionService.java.
Referenced by ch.zhaw.ba10_bsha_1.service.DetectionService.initDetection().
final RemoteCallbackList<IReturnResults> ch.zhaw.ba10_bsha_1.service.DetectionService.callbacks = new RemoteCallbackList<IReturnResults>() [package]
This is a list of callbacks that have been registered with the service. Note that this is package scoped (instead of private) so that it can be accessed more efficiently from inner classes.
Definition at line 70 of file DetectionService.java.
Referenced by ch.zhaw.ba10_bsha_1.service.DetectionService.onDestroy(), and ch.zhaw.ba10_bsha_1.service.DetectionService.startDetection().
ICharacterDetectionStrategy ch.zhaw.ba10_bsha_1.service.DetectionService.charDetectionStrategy [private]
Definition at line 79 of file DetectionService.java.
Referenced by ch.zhaw.ba10_bsha_1.service.DetectionService.initDetection(), and ch.zhaw.ba10_bsha_1.service.DetectionService.startDetection().
Context ch.zhaw.ba10_bsha_1.service.DetectionService.CONTEXT [static, private]
Definition at line 63 of file DetectionService.java.
Referenced by ch.zhaw.ba10_bsha_1.service.DetectionService.getContext(), and ch.zhaw.ba10_bsha_1.service.DetectionService.onCreate().
final boolean ch.zhaw.ba10_bsha_1.service.DetectionService.DEBUG = true [private]
Definition at line 72 of file DetectionService.java.
Referenced by ch.zhaw.ba10_bsha_1.service.DetectionService.startDetection().
ArrayList<TouchPoint> ch.zhaw.ba10_bsha_1.service.DetectionService.inputPoints [private]
Definition at line 74 of file DetectionService.java.
Referenced by ch.zhaw.ba10_bsha_1.service.DetectionService.initDetection(), and ch.zhaw.ba10_bsha_1.service.DetectionService.startDetection().
StrategyQueue<IMicroGestureDetectionStrategy> ch.zhaw.ba10_bsha_1.service.DetectionService.mgDetectionSteps [private]
Definition at line 78 of file DetectionService.java.
Referenced by ch.zhaw.ba10_bsha_1.service.DetectionService.initDetection(), and ch.zhaw.ba10_bsha_1.service.DetectionService.startDetection().
NotificationManager ch.zhaw.ba10_bsha_1.service.DetectionService.notificationManager [private]
Definition at line 82 of file DetectionService.java.
Referenced by ch.zhaw.ba10_bsha_1.service.DetectionService.onCreate(), ch.zhaw.ba10_bsha_1.service.DetectionService.onDestroy(), and ch.zhaw.ba10_bsha_1.service.DetectionService.showNotification().
IPostprocessingStrategy ch.zhaw.ba10_bsha_1.service.DetectionService.postprocessingStrategy [private]
Definition at line 80 of file DetectionService.java.
Referenced by ch.zhaw.ba10_bsha_1.service.DetectionService.initDetection(), and ch.zhaw.ba10_bsha_1.service.DetectionService.startDetection().
StrategyQueue<IPreprocessingStrategy> ch.zhaw.ba10_bsha_1.service.DetectionService.preprocessingSteps [private]
Definition at line 77 of file DetectionService.java.
Referenced by ch.zhaw.ba10_bsha_1.service.DetectionService.initDetection(), and ch.zhaw.ba10_bsha_1.service.DetectionService.startDetection().
final IDetectionService.Stub ch.zhaw.ba10_bsha_1.service.DetectionService.serviceBinder [private]
The IDetectionService Interface as defined through AIDL
Definition at line 253 of file DetectionService.java.
Referenced by ch.zhaw.ba10_bsha_1.service.DetectionService.onBind().
final int ch.zhaw.ba10_bsha_1.service.DetectionService.STRATEGY_TYPE_CHARACTER_DETECTION = 2 [static, private]
Definition at line 59 of file DetectionService.java.
Referenced by ch.zhaw.ba10_bsha_1.service.DetectionService.getManagerByType().
final int ch.zhaw.ba10_bsha_1.service.DetectionService.STRATEGY_TYPE_MICROGESTURE_DETECTION = 1 [static, private]
Definition at line 58 of file DetectionService.java.
Referenced by ch.zhaw.ba10_bsha_1.service.DetectionService.getManagerByType().
final int ch.zhaw.ba10_bsha_1.service.DetectionService.STRATEGY_TYPE_POSTPROCESSING = 3 [static, private]
Definition at line 60 of file DetectionService.java.
Referenced by ch.zhaw.ba10_bsha_1.service.DetectionService.getManagerByType().
final int ch.zhaw.ba10_bsha_1.service.DetectionService.STRATEGY_TYPE_PREPROCESSING = 0 [static, private]
Definition at line 57 of file DetectionService.java.
Referenced by ch.zhaw.ba10_bsha_1.service.DetectionService.getManagerByType().
final String ch.zhaw.ba10_bsha_1.service.DetectionService.TAG = "DetectionService" [static, private]
Definition at line 62 of file DetectionService.java.
Referenced by ch.zhaw.ba10_bsha_1.service.DetectionService.startDetection().
The documentation for this class was generated from the following file:
/media/Daten/Studium/BA/source/BA10-bsha-1/src/ch/zhaw/ba10_bsha_1/service/DetectionService.java