BA10-bsha-1: ch.zhaw.ba10_bsha_1.ime.HandwritingIME Class Reference
ch.zhaw.ba10_bsha_1.ime.HandwritingIME Class Reference
Inherits android::inputmethodservice::InputMethodService, and ch::zhaw::ba10_bsha_1::ime::IObserver.
Classes
class DetectionServiceConnection
Public Member Functions
void onCreate ()
void onInitializeInterface ()
View onCreateInputView ()
void onStartInputView (EditorInfo attribute, boolean restarting)
void onDestroy ()
void update (IObservable updater)
View onCreateCandidatesView ()
void onStartInput (EditorInfo attribute, boolean restarting)
void onFinishInput ()
void onUpdateSelection (int oldSelStart, int oldSelEnd, int newSelStart, int newSelEnd, int candidatesStart, int candidatesEnd)
void onDisplayCompletions (CompletionInfo[] completion_infos)
boolean onKeyDown (int keyCode, KeyEvent event)
boolean onKeyUp (int keyCode, KeyEvent event)
void onKey (int primaryCode, int[] keyCodes)
void onText (CharSequence text)
void setSuggestions (List< String > suggestions, boolean completions, boolean typedWordValid)
boolean isWordSeparator (int code)
void pickDefaultCandidate ()
void pickSuggestionManually (int index)
void swipeRight ()
void swipeLeft ()
void swipeDown ()
void swipeUp ()
void onPress (int primaryCode)
void onRelease (int primaryCode)
Private Member Functions
boolean translateKeyDown (int keyCode, KeyEvent event)
void commitTyped (InputConnection inputConnection)
boolean isAlphabet (int code)
void keyDownUp (int keyEventCode)
void sendKey (int keyCode)
void updateCandidates ()
void handleBackspace ()
void handleCharacter (int primaryCode, int[] keyCodes)
void handleClose ()
String getWordSeparators ()
Private Attributes
IDetectionService detectionService = null
DetectionServiceConnection serviceConnection
boolean serviceIsBound = false
boolean serviceIsRunning = false
PadView padView
boolean sendFieldHeight = false
CandidateView candidateView
CompletionInfo[] completions
StringBuilder composingText = new StringBuilder()
boolean predictionOn
boolean completionOn
long metaState
LatinKeyboard padKeyboard
LatinKeyboard curKeyboard
String wordSeparators
IReturnResults serviceCallback
Handler serviceHandler
Static Private Attributes
static final boolean PROCESS_HARD_KEYS = true
static final int CHARACTER_RESULT_MSG = 1
static final int CHAR_RESULT_MSG = 2
Detailed Description
A basic implementation of the InputMethodService for our IME. Deals with the connection to the DetectionService and lets a PadView handle the gathering of the input data.
Based on the SoftKeyboard example from the Android SDK.
Definition at line 45 of file HandwritingIME.java.
Member Function Documentation
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.commitTyped (InputConnection inputConnection) [private]
Helper function to commit any text being composed in to the editor.
Definition at line 580 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.HandwritingIME.composingText, and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.updateCandidates().
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.handleClose(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onKey(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onText(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.pickSuggestionManually().
String ch.zhaw.ba10_bsha_1.ime.HandwritingIME.getWordSeparators () [private]
Definition at line 728 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.HandwritingIME.wordSeparators.
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.isWordSeparator().
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.handleBackspace () [private]
Clean up text suggestions if needed and send the keycode for the backspace-key.
Definition at line 691 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.HandwritingIME.composingText, ch.zhaw.ba10_bsha_1.ime.HandwritingIME.keyDownUp(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.updateCandidates().
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onKey(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.swipeLeft(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.update().
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.handleCharacter (int primaryCode, int[] keyCodes) [private]
Add character to suggestion of needed or send directly through the InputConnection
Definition at line 709 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.HandwritingIME.composingText, ch.zhaw.ba10_bsha_1.ime.HandwritingIME.isAlphabet(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.predictionOn, and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.updateCandidates().
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onKey().
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.handleClose () [private]
React on closing of the input method
Definition at line 722 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.PadView.closing(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.commitTyped(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.padView.
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onKey(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.swipeDown().
boolean ch.zhaw.ba10_bsha_1.ime.HandwritingIME.isAlphabet (int code) [private]
Helper to determine if a given character code is alphabetic.
Definition at line 591 of file HandwritingIME.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.handleCharacter().
boolean ch.zhaw.ba10_bsha_1.ime.HandwritingIME.isWordSeparator (int code)
Definition at line 732 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.HandwritingIME.getWordSeparators().
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onKey().
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.keyDownUp (int keyEventCode) [private]
Helper to send a key down / key up pair to the current editor.
Definition at line 602 of file HandwritingIME.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.handleBackspace(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.sendKey().
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onCreate ()
Main initialization of the input method component. Used to start the service if it's not already running.
Definition at line 116 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.HandwritingIME.serviceConnection, ch.zhaw.ba10_bsha_1.ime.HandwritingIME.serviceIsRunning, and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.wordSeparators.
View ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onCreateCandidatesView ()
Called by the framework when the view for showing candidates needs to be generated, like onCreateInputView.
Definition at line 315 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.HandwritingIME.candidateView, and ch.zhaw.ba10_bsha_1.ime.CandidateView.setService().
View ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onCreateInputView ()
Called by the framework when the view for creating input needs to be generated. This will be called the first time the input method is displayed, and every time it needs to be re-created such as due to a configuration change.
Definition at line 147 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.HandwritingIME.padKeyboard, and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.padView.
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onDestroy ()
Called when the input method is destroy. Since there will be no input method around afterwards, we can use this to unbind the input method from the Service.
Definition at line 175 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.HandwritingIME.detectionService, ch.zhaw.ba10_bsha_1.ime.HandwritingIME.serviceCallback, ch.zhaw.ba10_bsha_1.ime.HandwritingIME.serviceConnection, and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.serviceIsBound.
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onDisplayCompletions (CompletionInfo[] completion_infos)
This tells us about completions that the editor has determined based on the current text in it. We want to use this in fullscreen mode to show the completions ourself, since the editor can not be seen in that situation.
Definition at line 463 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.HandwritingIME.completionOn, ch.zhaw.ba10_bsha_1.ime.HandwritingIME.completions, and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.setSuggestions().
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onFinishInput ()
This is called when the user is done editing a field. We can use this to reset our state.
Definition at line 419 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.PadView.closing(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.composingText, ch.zhaw.ba10_bsha_1.ime.HandwritingIME.padView, and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.updateCandidates().
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onInitializeInterface ()
Initialization of the User Interface. It is called after creation and any configuration change.
Definition at line 131 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.PadView.attachObserver(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.padKeyboard, and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.padView.
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onKey (int primaryCode, int[] keyCodes)
Implementation of KeyboardViewListener
See also:
android.inputmethodservice.KeyboardView.OnKeyboardActionListener.onKey(int, int[])
Definition at line 629 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.HandwritingIME.commitTyped(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.composingText, ch.zhaw.ba10_bsha_1.ime.HandwritingIME.handleBackspace(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.handleCharacter(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.handleClose(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.isWordSeparator(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.sendKey().
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onKeyDown(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.translateKeyDown().
boolean ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onKeyDown (int keyCode, KeyEvent event)
Use this to monitor key events being delivered to the application. We get first crack at them, and can either resume them or let them continue to the app.
Definition at line 521 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.HandwritingIME.composingText, ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onKey(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.padView, ch.zhaw.ba10_bsha_1.ime.HandwritingIME.predictionOn, ch.zhaw.ba10_bsha_1.ime.HandwritingIME.PROCESS_HARD_KEYS, and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.translateKeyDown().
boolean ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onKeyUp (int keyCode, KeyEvent event)
Use this to monitor key events being delivered to the application. We get first crack at them, and can either resume them or let them continue to the app.
Definition at line 565 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.HandwritingIME.metaState, ch.zhaw.ba10_bsha_1.ime.HandwritingIME.predictionOn, and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.PROCESS_HARD_KEYS.
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onPress (int primaryCode)
Definition at line 775 of file HandwritingIME.java.
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onRelease (int primaryCode)
Definition at line 776 of file HandwritingIME.java.
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onStartInput (EditorInfo attribute, boolean restarting)
This is the main point where we do our initialization of the input method to begin operating on an application. At this point we have been bound to the client, and are now receiving all of the detailed information about the target of our edits.
Definition at line 328 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.HandwritingIME.completionOn, ch.zhaw.ba10_bsha_1.ime.HandwritingIME.completions, ch.zhaw.ba10_bsha_1.ime.HandwritingIME.composingText, ch.zhaw.ba10_bsha_1.ime.HandwritingIME.curKeyboard, ch.zhaw.ba10_bsha_1.ime.HandwritingIME.metaState, ch.zhaw.ba10_bsha_1.ime.HandwritingIME.padKeyboard, ch.zhaw.ba10_bsha_1.ime.HandwritingIME.predictionOn, ch.zhaw.ba10_bsha_1.ime.LatinKeyboard.setImeOptions(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.updateCandidates().
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onStartInputView (EditorInfo attribute, boolean restarting)
Called every time when the input method is shown, therefore we use this to bind to the Service.
Definition at line 163 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.PadView.closing(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.curKeyboard, ch.zhaw.ba10_bsha_1.ime.HandwritingIME.padView, ch.zhaw.ba10_bsha_1.ime.HandwritingIME.serviceConnection, and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.serviceIsBound.
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onText (CharSequence text)
Definition at line 646 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.HandwritingIME.commitTyped(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.composingText.
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onUpdateSelection (int oldSelStart, int oldSelEnd, int newSelStart, int newSelEnd, int candidatesStart, int candidatesEnd)
Deal with the editor reporting movement of its cursor.
Definition at line 440 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.HandwritingIME.composingText, and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.updateCandidates().
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.pickDefaultCandidate ()
Pick the first suggested candidate
Definition at line 740 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.HandwritingIME.pickSuggestionManually().
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.pickSuggestionManually (int index)
Pick one of the suggested candidates
Parameters:
index
Definition at line 748 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.HandwritingIME.candidateView, ch.zhaw.ba10_bsha_1.ime.CandidateView.clear(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.commitTyped(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.completionOn, ch.zhaw.ba10_bsha_1.ime.HandwritingIME.completions, and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.composingText.
Referenced by ch.zhaw.ba10_bsha_1.ime.CandidateView.onTouchEvent(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.pickDefaultCandidate(), and ch.zhaw.ba10_bsha_1.ime.CandidateView.takeSuggestionAt().
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.sendKey (int keyCode) [private]
Helper to send a character to the editor as raw key events.
Definition at line 610 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.HandwritingIME.keyDownUp().
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onKey().
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.setSuggestions (List< String > suggestions, boolean completions, boolean typedWordValid)
Definition at line 676 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.HandwritingIME.candidateView, and ch.zhaw.ba10_bsha_1.ime.CandidateView.setSuggestions().
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onDisplayCompletions(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.updateCandidates().
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.swipeDown ()
Definition at line 770 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.HandwritingIME.handleClose().
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.swipeLeft ()
Definition at line 766 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.HandwritingIME.handleBackspace().
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.swipeRight ()
Definition at line 764 of file HandwritingIME.java.
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.swipeUp ()
Definition at line 774 of file HandwritingIME.java.
boolean ch.zhaw.ba10_bsha_1.ime.HandwritingIME.translateKeyDown (int keyCode, KeyEvent event) [private]
This translates incoming hard key events in to edit operations on an InputConnection. It is only needed when using the PROCESS_HARD_KEYS option.
Definition at line 485 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.HandwritingIME.composingText, ch.zhaw.ba10_bsha_1.ime.HandwritingIME.metaState, and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onKey().
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onKeyDown().
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.update (IObservable updater)
Deal with changes in the PadView, mostly relaying its input to the DetectionService
Implements ch.zhaw.ba10_bsha_1.ime.IObserver.
Definition at line 199 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.HandwritingIME.detectionService, ch.zhaw.ba10_bsha_1.ime.PadView.getEventType(), ch.zhaw.ba10_bsha_1.ime.PadView.getLastPoints(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.handleBackspace(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.padView, ch.zhaw.ba10_bsha_1.ime.HandwritingIME.sendFieldHeight, and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.serviceIsBound.
void ch.zhaw.ba10_bsha_1.ime.HandwritingIME.updateCandidates () [private]
Update the list of available candidates from the current composing text. This will need to be filled in by however you are determining candidates.
Definition at line 664 of file HandwritingIME.java.
References ch.zhaw.ba10_bsha_1.ime.HandwritingIME.completionOn, ch.zhaw.ba10_bsha_1.ime.HandwritingIME.composingText, and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.setSuggestions().
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.commitTyped(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.handleBackspace(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.handleCharacter(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onFinishInput(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onStartInput(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onUpdateSelection().
Member Data Documentation
CandidateView ch.zhaw.ba10_bsha_1.ime.HandwritingIME.candidateView [private]
Definition at line 93 of file HandwritingIME.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onCreateCandidatesView(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.pickSuggestionManually(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.setSuggestions().
final int ch.zhaw.ba10_bsha_1.ime.HandwritingIME.CHAR_RESULT_MSG = 2 [static, private]
Definition at line 262 of file HandwritingIME.java.
final int ch.zhaw.ba10_bsha_1.ime.HandwritingIME.CHARACTER_RESULT_MSG = 1 [static, private]
Definition at line 261 of file HandwritingIME.java.
boolean ch.zhaw.ba10_bsha_1.ime.HandwritingIME.completionOn [private]
Definition at line 98 of file HandwritingIME.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onDisplayCompletions(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onStartInput(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.pickSuggestionManually(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.updateCandidates().
CompletionInfo [] ch.zhaw.ba10_bsha_1.ime.HandwritingIME.completions [private]
Definition at line 94 of file HandwritingIME.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onDisplayCompletions(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onStartInput(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.pickSuggestionManually().
StringBuilder ch.zhaw.ba10_bsha_1.ime.HandwritingIME.composingText = new StringBuilder() [private]
Definition at line 96 of file HandwritingIME.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.commitTyped(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.handleBackspace(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.handleCharacter(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onFinishInput(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onKey(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onKeyDown(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onStartInput(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onText(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onUpdateSelection(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.pickSuggestionManually(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.translateKeyDown(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.updateCandidates().
LatinKeyboard ch.zhaw.ba10_bsha_1.ime.HandwritingIME.curKeyboard [private]
Definition at line 102 of file HandwritingIME.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onStartInput(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onStartInputView().
IDetectionService ch.zhaw.ba10_bsha_1.ime.HandwritingIME.detectionService = null [private]
Definition at line 86 of file HandwritingIME.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onDestroy(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.DetectionServiceConnection.onServiceConnected(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.DetectionServiceConnection.onServiceDisconnected(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.update().
long ch.zhaw.ba10_bsha_1.ime.HandwritingIME.metaState [private]
Definition at line 99 of file HandwritingIME.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onKeyUp(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onStartInput(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.translateKeyDown().
LatinKeyboard ch.zhaw.ba10_bsha_1.ime.HandwritingIME.padKeyboard [private]
Definition at line 101 of file HandwritingIME.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onCreateInputView(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onInitializeInterface(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onStartInput().
PadView ch.zhaw.ba10_bsha_1.ime.HandwritingIME.padView [private]
Definition at line 91 of file HandwritingIME.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.handleClose(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onCreateInputView(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onFinishInput(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onInitializeInterface(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onKeyDown(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onStartInputView(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.update().
boolean ch.zhaw.ba10_bsha_1.ime.HandwritingIME.predictionOn [private]
Definition at line 97 of file HandwritingIME.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.handleCharacter(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onKeyDown(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onKeyUp(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onStartInput().
final boolean ch.zhaw.ba10_bsha_1.ime.HandwritingIME.PROCESS_HARD_KEYS = true [static, private]
Definition at line 84 of file HandwritingIME.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onKeyDown(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onKeyUp().
boolean ch.zhaw.ba10_bsha_1.ime.HandwritingIME.sendFieldHeight = false [private]
Definition at line 92 of file HandwritingIME.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.update().
IReturnResults ch.zhaw.ba10_bsha_1.ime.HandwritingIME.serviceCallback [private]
Initial value:
 new IReturnResults.Stub() {
                @Override
                public void recognisedCharacters(List<ch.zhaw.ba10_bsha_1.Character> characters) throws RemoteException {
                        serviceHandler.sendMessage(serviceHandler.obtainMessage(CHARACTER_RESULT_MSG, characters));
                }
                @Override
                public void recognisedChar(char character, float probability) throws RemoteException {
                        serviceHandler.sendMessage(serviceHandler.obtainMessage(CHAR_RESULT_MSG, character, Math.round(probability * 1000000)));
                }
    }
This implementation is used to receive callbacks from the remote service.
Definition at line 249 of file HandwritingIME.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onDestroy(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.DetectionServiceConnection.onServiceConnected().
DetectionServiceConnection ch.zhaw.ba10_bsha_1.ime.HandwritingIME.serviceConnection [private]
Definition at line 87 of file HandwritingIME.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onCreate(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onDestroy(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onStartInputView().
Handler ch.zhaw.ba10_bsha_1.ime.HandwritingIME.serviceHandler [private]
Definition at line 264 of file HandwritingIME.java.
boolean ch.zhaw.ba10_bsha_1.ime.HandwritingIME.serviceIsBound = false [private]
Definition at line 88 of file HandwritingIME.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onDestroy(), ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onStartInputView(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.update().
boolean ch.zhaw.ba10_bsha_1.ime.HandwritingIME.serviceIsRunning = false [private]
Definition at line 89 of file HandwritingIME.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onCreate().
String ch.zhaw.ba10_bsha_1.ime.HandwritingIME.wordSeparators [private]
Definition at line 104 of file HandwritingIME.java.
Referenced by ch.zhaw.ba10_bsha_1.ime.HandwritingIME.getWordSeparators(), and ch.zhaw.ba10_bsha_1.ime.HandwritingIME.onCreate().
The documentation for this class was generated from the following file:
/media/Daten/Studium/BA/source/BA10-bsha-1/src/ch/zhaw/ba10_bsha_1/ime/HandwritingIME.java