BA10-bsha-1: ch.zhaw.ba10_bsha_1.service.MicroGesture Class Reference
ch.zhaw.ba10_bsha_1.service.MicroGesture Class Reference
Inherits android::os::Parcelable.
Public Member Functions
MicroGesture ()
MicroGesture (Collection< TouchPoint > points)
MicroGesture (Collection< TouchPoint > points, int type, int direction)
MicroGesture (Parcel source)
Object clone () throws CloneNotSupportedException
int describeContents ()
void writeToParcel (Parcel dest, int flags)
void readFromParcel (Parcel source)
boolean canMergeStubs ()
void enableStubMerging (boolean merge_stubs)
MicroGesture merge (MicroGesture other)
boolean canMergeWith (MicroGesture other)
float getLength ()
Path getPath ()
void drawPath (Canvas canvas, int color)
boolean hasKnownType ()
int getType ()
void setType (int type)
boolean directionIsUp ()
boolean directionIsDown ()
boolean directionIsRight ()
boolean directionIsLeft ()
int getDirection ()
void setDirection (int direction)
boolean directionHasSwitched ()
void setDirectionSwitched (boolean switched_direction)
ArrayList< TouchPoint > getPoints ()
void setPoints (Collection< TouchPoint > p)
void addPoint (float x, float y)
void addPoint (TouchPoint point)
String toString ()
String getPointList ()
Static Public Member Functions
static int StrToType (String str)
Static Public Attributes
static final int TYPE_UNKNOWN = -1
static final int TYPE_WIDE_CURVE = 0
static final int TYPE_NARROW_CURVE = 1
static final int TYPE_LONG_LINE = 2
static final int TYPE_SHORT_LINE = 3
static final int TYPE_CIRCLE = 4
static final int TYPE_HALFCIRCLE = 5
static final int TYPE_DOT = 6
static final
Parcelable.Creator
< MicroGesture > CREATOR
Private Attributes
int type
int direction
boolean switchedDirection
ArrayList< TouchPoint > points
boolean mergeStubs
Detailed Description
Represents a MicroGesture, a minimal gesture in which we want separate our input point. Implements Parcelable and can therefore be send to and from a service.
Author:
Julian Hanhart, Dominik Giger
Definition at line 23 of file MicroGesture.java.
Constructor & Destructor Documentation
ch.zhaw.ba10_bsha_1.service.MicroGesture.MicroGesture ()
Definition at line 53 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.direction, ch.zhaw.ba10_bsha_1.service.MicroGesture.mergeStubs, ch.zhaw.ba10_bsha_1.service.MicroGesture.points, ch.zhaw.ba10_bsha_1.service.MicroGesture.switchedDirection, ch.zhaw.ba10_bsha_1.service.MicroGesture.type, and ch.zhaw.ba10_bsha_1.service.MicroGesture.TYPE_UNKNOWN.
ch.zhaw.ba10_bsha_1.service.MicroGesture.MicroGesture (Collection< TouchPoint > points)
Definition at line 61 of file MicroGesture.java.
ch.zhaw.ba10_bsha_1.service.MicroGesture.MicroGesture (Collection< TouchPoint > points, int type, int direction)
Definition at line 66 of file MicroGesture.java.
ch.zhaw.ba10_bsha_1.service.MicroGesture.MicroGesture (Parcel source)
Definition at line 72 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.readFromParcel().
Member Function Documentation
void ch.zhaw.ba10_bsha_1.service.MicroGesture.addPoint (TouchPoint point)
Definition at line 306 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.points.
void ch.zhaw.ba10_bsha_1.service.MicroGesture.addPoint (float x, float y)
Definition at line 302 of file MicroGesture.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.detectMicroGestures(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.detectMicroGestures(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle.detectMicroGestures(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyEdges.detectMicroGestures(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.detectMicroGestures(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCombine.detectMicroGestures(), and ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCircles.detectMicroGestures().
boolean ch.zhaw.ba10_bsha_1.service.MicroGesture.canMergeStubs ()
Definition at line 135 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.mergeStubs.
boolean ch.zhaw.ba10_bsha_1.service.MicroGesture.canMergeWith (MicroGesture other)
Determine whether we can merge this MircoGesture with another
Parameters:
other
Returns:
Definition at line 167 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.direction, ch.zhaw.ba10_bsha_1.service.MicroGesture.mergeStubs, ch.zhaw.ba10_bsha_1.service.MicroGesture.points, and ch.zhaw.ba10_bsha_1.service.MicroGesture.type.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.analyseMicroGesture(), and ch.zhaw.ba10_bsha_1.service.MicroGesture.merge().
Object ch.zhaw.ba10_bsha_1.service.MicroGesture.clone () throws CloneNotSupportedException
Definition at line 76 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.direction, ch.zhaw.ba10_bsha_1.service.MicroGesture.points, ch.zhaw.ba10_bsha_1.service.MicroGesture.switchedDirection, and ch.zhaw.ba10_bsha_1.service.MicroGesture.type.
int ch.zhaw.ba10_bsha_1.service.MicroGesture.describeContents ()
Definition at line 106 of file MicroGesture.java.
boolean ch.zhaw.ba10_bsha_1.service.MicroGesture.directionHasSwitched ()
Definition at line 284 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.switchedDirection.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGestureTester.validate().
boolean ch.zhaw.ba10_bsha_1.service.MicroGesture.directionIsDown ()
Definition at line 262 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.direction.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGestureTester.validate().
boolean ch.zhaw.ba10_bsha_1.service.MicroGesture.directionIsLeft ()
Definition at line 270 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.direction.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGestureTester.validate().
boolean ch.zhaw.ba10_bsha_1.service.MicroGesture.directionIsRight ()
Definition at line 266 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.direction.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGestureTester.validate().
boolean ch.zhaw.ba10_bsha_1.service.MicroGesture.directionIsUp ()
Definition at line 258 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.direction.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGestureTester.validate().
void ch.zhaw.ba10_bsha_1.service.MicroGesture.drawPath (Canvas canvas, int color)
Draw the MicroGesture's Path on the given Canvas in the given color
Parameters:
canvas
color
Definition at line 219 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.getPath(), and ch.zhaw.ba10_bsha_1.service.MicroGesture.points.
void ch.zhaw.ba10_bsha_1.service.MicroGesture.enableStubMerging (boolean merge_stubs)
Definition at line 139 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.mergeStubs.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.analyseMicroGesture().
int ch.zhaw.ba10_bsha_1.service.MicroGesture.getDirection ()
Definition at line 275 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.direction.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.detectMicroGestures(), and ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCombine.detectMicroGestures().
float ch.zhaw.ba10_bsha_1.service.MicroGesture.getLength ()
Calculate the overall length of this MicroGesture (point to point distances)
Definition at line 182 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.points.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.analyseMicroGestureType().
Path ch.zhaw.ba10_bsha_1.service.MicroGesture.getPath ()
Create a Path out of the MicroGesture's points
Returns:
Definition at line 195 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.points.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGesture.drawPath().
String ch.zhaw.ba10_bsha_1.service.MicroGesture.getPointList ()
Get a list of all the MicroGesture's points as a String
Returns:
Definition at line 351 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.points.
ArrayList<TouchPoint> ch.zhaw.ba10_bsha_1.service.MicroGesture.getPoints ()
Definition at line 293 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.points.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.analyseMicroGestureDirection(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.analyseMicroGestureDirection(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle.analyseMicroGestureDirection(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.analyseMicroGestureDirection(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.analyseMicroGestureType(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.detectMicroGestures(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.detectMicroGestures(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.detectMicroGestures(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCombine.detectMicroGestures(), ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyNormalizePoints.process(), ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog.process(), ch.zhaw.ba10_bsha_1.strategies.PathSmoothingStrategySpline.process(), ch.zhaw.ba10_bsha_1.strategies.PathSmoothingStrategyAverage.process(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.setMicroGesture(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle.setMicroGesture(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.setMicroGesture(), and ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCombine.setMicroGesture().
int ch.zhaw.ba10_bsha_1.service.MicroGesture.getType ()
Definition at line 250 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.type.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.analyseMicroGestureDirection(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle.analyseMicroGestureDirection(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.detectMicroGestures(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCombine.detectMicroGestures(), and ch.zhaw.ba10_bsha_1.service.MicroGestureTester.validate().
boolean ch.zhaw.ba10_bsha_1.service.MicroGesture.hasKnownType ()
Definition at line 246 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.type.
MicroGesture ch.zhaw.ba10_bsha_1.service.MicroGesture.merge (MicroGesture other)
Determine whether we can merge this MircoGesture with another and do so if we can
Parameters:
other
Returns:
Definition at line 150 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.canMergeWith(), and ch.zhaw.ba10_bsha_1.service.MicroGesture.points.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.analyseMicroGesture().
void ch.zhaw.ba10_bsha_1.service.MicroGesture.readFromParcel (Parcel source)
Definition at line 119 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.direction, ch.zhaw.ba10_bsha_1.service.MicroGesture.points, ch.zhaw.ba10_bsha_1.service.MicroGesture.switchedDirection, and ch.zhaw.ba10_bsha_1.service.MicroGesture.type.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGesture.MicroGesture().
void ch.zhaw.ba10_bsha_1.service.MicroGesture.setDirection (int direction)
Definition at line 279 of file MicroGesture.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.analyseMicroGesture(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.analyseMicroGestureDirection(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle.analyseMicroGestureDirection(), and ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.detectMicroGestures().
void ch.zhaw.ba10_bsha_1.service.MicroGesture.setDirectionSwitched (boolean switched_direction)
Definition at line 288 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.switchedDirection.
void ch.zhaw.ba10_bsha_1.service.MicroGesture.setPoints (Collection< TouchPoint > p)
Definition at line 297 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.points.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyEdges.detectMicroGestures(), and ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyNormalizePoints.process().
void ch.zhaw.ba10_bsha_1.service.MicroGesture.setType (int type)
Definition at line 254 of file MicroGesture.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.analyseMicroGesture(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyEdges.detectMicroGestures(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCircles.detectMicroGestures(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines.setMicroGesture(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle.setMicroGesture(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature.setMicroGesture(), and ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCombine.setMicroGesture().
static int ch.zhaw.ba10_bsha_1.service.MicroGesture.StrToType (String str) [static]
Translate the given String-representation of a MicroGesture-Type to its integer value
Parameters:
str
Returns:
Definition at line 373 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.type, ch.zhaw.ba10_bsha_1.service.MicroGesture.TYPE_CIRCLE, ch.zhaw.ba10_bsha_1.service.MicroGesture.TYPE_DOT, ch.zhaw.ba10_bsha_1.service.MicroGesture.TYPE_HALFCIRCLE, ch.zhaw.ba10_bsha_1.service.MicroGesture.TYPE_LONG_LINE, ch.zhaw.ba10_bsha_1.service.MicroGesture.TYPE_NARROW_CURVE, ch.zhaw.ba10_bsha_1.service.MicroGesture.TYPE_SHORT_LINE, ch.zhaw.ba10_bsha_1.service.MicroGesture.TYPE_UNKNOWN, and ch.zhaw.ba10_bsha_1.service.MicroGesture.TYPE_WIDE_CURVE.
String ch.zhaw.ba10_bsha_1.service.MicroGesture.toString ()
Definition at line 311 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.direction, ch.zhaw.ba10_bsha_1.service.MicroGesture.points, ch.zhaw.ba10_bsha_1.service.MicroGesture.type, ch.zhaw.ba10_bsha_1.service.MicroGesture.TYPE_CIRCLE, ch.zhaw.ba10_bsha_1.service.MicroGesture.TYPE_DOT, ch.zhaw.ba10_bsha_1.service.MicroGesture.TYPE_HALFCIRCLE, ch.zhaw.ba10_bsha_1.service.MicroGesture.TYPE_LONG_LINE, ch.zhaw.ba10_bsha_1.service.MicroGesture.TYPE_NARROW_CURVE, ch.zhaw.ba10_bsha_1.service.MicroGesture.TYPE_SHORT_LINE, and ch.zhaw.ba10_bsha_1.service.MicroGesture.TYPE_WIDE_CURVE.
void ch.zhaw.ba10_bsha_1.service.MicroGesture.writeToParcel (Parcel dest, int flags)
Definition at line 111 of file MicroGesture.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.direction, ch.zhaw.ba10_bsha_1.service.MicroGesture.points, ch.zhaw.ba10_bsha_1.service.MicroGesture.switchedDirection, and ch.zhaw.ba10_bsha_1.service.MicroGesture.type.
Member Data Documentation
final Parcelable.Creator<MicroGesture> ch.zhaw.ba10_bsha_1.service.MicroGesture.CREATOR [static]
Initial value:
 new Parcelable.Creator<MicroGesture>() {
                public MicroGesture createFromParcel(Parcel in) {
                        return new MicroGesture(in);
                }
                public MicroGesture[] newArray(int size) {
                        return new MicroGesture[size];
                }
        }
Definition at line 88 of file MicroGesture.java.
int ch.zhaw.ba10_bsha_1.service.MicroGesture.direction [private]
Definition at line 41 of file MicroGesture.java.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGesture.canMergeWith(), ch.zhaw.ba10_bsha_1.service.MicroGesture.clone(), ch.zhaw.ba10_bsha_1.service.MicroGesture.directionIsDown(), ch.zhaw.ba10_bsha_1.service.MicroGesture.directionIsLeft(), ch.zhaw.ba10_bsha_1.service.MicroGesture.directionIsRight(), ch.zhaw.ba10_bsha_1.service.MicroGesture.directionIsUp(), ch.zhaw.ba10_bsha_1.service.MicroGesture.getDirection(), ch.zhaw.ba10_bsha_1.service.MicroGesture.MicroGesture(), ch.zhaw.ba10_bsha_1.service.MicroGesture.readFromParcel(), ch.zhaw.ba10_bsha_1.service.MicroGesture.toString(), and ch.zhaw.ba10_bsha_1.service.MicroGesture.writeToParcel().
boolean ch.zhaw.ba10_bsha_1.service.MicroGesture.mergeStubs [private]
Definition at line 45 of file MicroGesture.java.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGesture.canMergeStubs(), ch.zhaw.ba10_bsha_1.service.MicroGesture.canMergeWith(), ch.zhaw.ba10_bsha_1.service.MicroGesture.enableStubMerging(), and ch.zhaw.ba10_bsha_1.service.MicroGesture.MicroGesture().
ArrayList<TouchPoint> ch.zhaw.ba10_bsha_1.service.MicroGesture.points [private]
Definition at line 43 of file MicroGesture.java.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGesture.addPoint(), ch.zhaw.ba10_bsha_1.service.MicroGesture.canMergeWith(), ch.zhaw.ba10_bsha_1.service.MicroGesture.clone(), ch.zhaw.ba10_bsha_1.service.MicroGesture.drawPath(), ch.zhaw.ba10_bsha_1.service.MicroGesture.getLength(), ch.zhaw.ba10_bsha_1.service.MicroGesture.getPath(), ch.zhaw.ba10_bsha_1.service.MicroGesture.getPointList(), ch.zhaw.ba10_bsha_1.service.MicroGesture.getPoints(), ch.zhaw.ba10_bsha_1.service.MicroGesture.merge(), ch.zhaw.ba10_bsha_1.service.MicroGesture.MicroGesture(), ch.zhaw.ba10_bsha_1.service.MicroGesture.readFromParcel(), ch.zhaw.ba10_bsha_1.service.MicroGesture.setPoints(), ch.zhaw.ba10_bsha_1.service.MicroGesture.toString(), and ch.zhaw.ba10_bsha_1.service.MicroGesture.writeToParcel().
boolean ch.zhaw.ba10_bsha_1.service.MicroGesture.switchedDirection [private]
Definition at line 42 of file MicroGesture.java.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGesture.clone(), ch.zhaw.ba10_bsha_1.service.MicroGesture.directionHasSwitched(), ch.zhaw.ba10_bsha_1.service.MicroGesture.MicroGesture(), ch.zhaw.ba10_bsha_1.service.MicroGesture.readFromParcel(), ch.zhaw.ba10_bsha_1.service.MicroGesture.setDirectionSwitched(), and ch.zhaw.ba10_bsha_1.service.MicroGesture.writeToParcel().
int ch.zhaw.ba10_bsha_1.service.MicroGesture.type [private]
Definition at line 40 of file MicroGesture.java.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGesture.canMergeWith(), ch.zhaw.ba10_bsha_1.service.MicroGesture.clone(), ch.zhaw.ba10_bsha_1.service.MicroGesture.getType(), ch.zhaw.ba10_bsha_1.service.MicroGesture.hasKnownType(), ch.zhaw.ba10_bsha_1.service.MicroGesture.MicroGesture(), ch.zhaw.ba10_bsha_1.service.MicroGesture.readFromParcel(), ch.zhaw.ba10_bsha_1.service.MicroGesture.StrToType(), ch.zhaw.ba10_bsha_1.service.MicroGesture.toString(), and ch.zhaw.ba10_bsha_1.service.MicroGesture.writeToParcel().
final int ch.zhaw.ba10_bsha_1.service.MicroGesture.TYPE_CIRCLE = 4 [static]
Definition at line 36 of file MicroGesture.java.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGesture.StrToType(), and ch.zhaw.ba10_bsha_1.service.MicroGesture.toString().
final int ch.zhaw.ba10_bsha_1.service.MicroGesture.TYPE_DOT = 6 [static]
Definition at line 38 of file MicroGesture.java.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGesture.StrToType(), and ch.zhaw.ba10_bsha_1.service.MicroGesture.toString().
final int ch.zhaw.ba10_bsha_1.service.MicroGesture.TYPE_HALFCIRCLE = 5 [static]
Definition at line 37 of file MicroGesture.java.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGesture.StrToType(), and ch.zhaw.ba10_bsha_1.service.MicroGesture.toString().
final int ch.zhaw.ba10_bsha_1.service.MicroGesture.TYPE_LONG_LINE = 2 [static]
Definition at line 34 of file MicroGesture.java.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGesture.StrToType(), and ch.zhaw.ba10_bsha_1.service.MicroGesture.toString().
final int ch.zhaw.ba10_bsha_1.service.MicroGesture.TYPE_NARROW_CURVE = 1 [static]
Definition at line 33 of file MicroGesture.java.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGesture.StrToType(), and ch.zhaw.ba10_bsha_1.service.MicroGesture.toString().
final int ch.zhaw.ba10_bsha_1.service.MicroGesture.TYPE_SHORT_LINE = 3 [static]
Definition at line 35 of file MicroGesture.java.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGesture.StrToType(), and ch.zhaw.ba10_bsha_1.service.MicroGesture.toString().
final int ch.zhaw.ba10_bsha_1.service.MicroGesture.TYPE_UNKNOWN = -1 [static]
Definition at line 31 of file MicroGesture.java.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGesture.MicroGesture(), and ch.zhaw.ba10_bsha_1.service.MicroGesture.StrToType().
final int ch.zhaw.ba10_bsha_1.service.MicroGesture.TYPE_WIDE_CURVE = 0 [static]
Definition at line 32 of file MicroGesture.java.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGesture.StrToType(), and ch.zhaw.ba10_bsha_1.service.MicroGesture.toString().
The documentation for this class was generated from the following file:
/media/Daten/Studium/BA/source/BA10-bsha-1/src/ch/zhaw/ba10_bsha_1/service/MicroGesture.java