BA10-bsha-1: ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyEdges Class Reference
ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyEdges Class Reference
Inherits ch::zhaw::ba10_bsha_1::strategies::BaseStrategy, and ch::zhaw::ba10_bsha_1::strategies::IMicroGestureDetectionStrategy.
Public Member Functions
void initialize ()
Collection< MicroGesture > detectMicroGestures (Collection< MicroGesture > microGestures)
Protected Member Functions
String getStrategyName ()
String getStrategyDescription ()
Private Attributes
double tolerance = 0.2d
double angleCosinus = -0.1d
Detailed Description
Implementation of IMicroGestureDetectionStrategy which detects edges in the paths of the TouchPoints of the given MicroGestures.
Author:
Dominik Giger, Julian Hanhart
Definition at line 17 of file MicroGestureDetectionStrategyEdges.java.
Member Function Documentation
Collection<MicroGesture> ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyEdges.detectMicroGestures (Collection< MicroGesture > microGestures)
Detect edges in the TouchPoints of the given MicroGestures
Parameters:
micro_gestures
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.IMicroGestureDetectionStrategy.
Definition at line 60 of file MicroGestureDetectionStrategyEdges.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.addPoint(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyEdges.angleCosinus, ch.zhaw.ba10_bsha_1.service.MicroGesture.setPoints(), ch.zhaw.ba10_bsha_1.service.MicroGesture.setType(), and ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyEdges.tolerance.
String ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyEdges.getStrategyDescription () [protected, virtual]
Return a description of the strategy
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 43 of file MicroGestureDetectionStrategyEdges.java.
String ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyEdges.getStrategyName () [protected, virtual]
Return the strategy's name
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 38 of file MicroGestureDetectionStrategyEdges.java.
void ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyEdges.initialize () [virtual]
Initialize the strategy's StrategyArguments
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 35 of file MicroGestureDetectionStrategyEdges.java.
Member Data Documentation
double ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyEdges.angleCosinus = -0.1d [private]
Definition at line 26 of file MicroGestureDetectionStrategyEdges.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyEdges.detectMicroGestures().
double ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyEdges.tolerance = 0.2d [private]
Definition at line 25 of file MicroGestureDetectionStrategyEdges.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyEdges.detectMicroGestures().
The documentation for this class was generated from the following file:
/media/Daten/Studium/BA/source/BA10-bsha-1/src/ch/zhaw/ba10_bsha_1/strategies/MicroGestureDetectionStrategyEdges.java