BA10-bsha-1: ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction Class Reference
ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction Class Reference
Inherits ch::zhaw::ba10_bsha_1::strategies::BaseStrategy, and ch::zhaw::ba10_bsha_1::strategies::IMicroGestureDetectionStrategy.
Public Member Functions
void initialize ()
Collection< MicroGesture > detectMicroGestures (Collection< MicroGesture > micro_gestures)
Protected Member Functions
String getStrategyName ()
String getStrategyDescription ()
Private Member Functions
MicroGesture analyseMicroGesture (ArrayList< MicroGesture > list, MicroGesture mg)
int analyseMicroGestureDirection (MicroGesture mg)
boolean directionIsUp (double direction)
boolean directionIsDown (double direction)
boolean directionIsRight (double direction)
boolean directionIsLeft (double direction)
int analyseMicroGestureType (MicroGesture mg)
float calcAngle (TouchPoint first, TouchPoint second, TouchPoint third)
Private Attributes
float predictionTolerance = 5
float fieldHeight = 0
boolean mergeMicroGestures = true
Detailed Description
Implementation of IMicroGestureDetectionStrategy which tries to distinguish between the different MicroGestures by using a prediction of the next point's position and starting a new MicroGesture if the actual next point is not within a certain tolerance of the predicted position. (Deprecated because the strategy was found ineffective and because it was not adjusted to changes in the overall design of the application)
Author:
Julian Hanhart, Dominik Giger
Definition at line 23 of file MicroGestureDetectionStrategyPrediction.java.
Member Function Documentation
MicroGesture ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.analyseMicroGesture (ArrayList< MicroGesture > list, MicroGesture mg) [private]
Determine a found MicroGesture's direction, type and merge it with the last one if needed
Parameters:
list
mg
Returns:
Definition at line 145 of file MicroGestureDetectionStrategyPrediction.java.
References ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.analyseMicroGestureDirection(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.analyseMicroGestureType(), ch.zhaw.ba10_bsha_1.service.MicroGesture.canMergeWith(), ch.zhaw.ba10_bsha_1.service.MicroGesture.enableStubMerging(), ch.zhaw.ba10_bsha_1.service.MicroGesture.merge(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.mergeMicroGestures, ch.zhaw.ba10_bsha_1.service.MicroGesture.setDirection(), and ch.zhaw.ba10_bsha_1.service.MicroGesture.setType().
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.detectMicroGestures().
int ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.analyseMicroGestureDirection (MicroGesture mg) [private]
Determine a MicroGesture's direction
Parameters:
mg
Returns:
Definition at line 164 of file MicroGestureDetectionStrategyPrediction.java.
References ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.directionIsDown(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.directionIsLeft(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.directionIsRight(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.directionIsUp(), and ch.zhaw.ba10_bsha_1.service.MicroGesture.getPoints().
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.analyseMicroGesture().
int ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.analyseMicroGestureType (MicroGesture mg) [private]
Determine a MicroGesture's type
Parameters:
mg
Returns:
Definition at line 218 of file MicroGestureDetectionStrategyPrediction.java.
References ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.calcAngle(), ch.zhaw.ba10_bsha_1.TouchPoint.distanceTo(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.fieldHeight, ch.zhaw.ba10_bsha_1.service.MicroGesture.getLength(), ch.zhaw.ba10_bsha_1.service.MicroGesture.getPoints(), and ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.predictionTolerance.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.analyseMicroGesture().
float ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.calcAngle (TouchPoint first, TouchPoint second, TouchPoint third) [private]
Calculate the angle between three TouchPoints
Parameters:
first
second
third
Returns:
Definition at line 250 of file MicroGestureDetectionStrategyPrediction.java.
References ch.zhaw.ba10_bsha_1.TouchPoint.distanceTo().
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.analyseMicroGestureType().
Collection<MicroGesture> ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.detectMicroGestures (Collection< MicroGesture > micro_gestures)
Detect MicroGestures in the TouchPoints of the given MicroGestures
Parameters:
micro_gestures
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.IMicroGestureDetectionStrategy.
Definition at line 71 of file MicroGestureDetectionStrategyPrediction.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.addPoint(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.analyseMicroGesture(), ch.zhaw.ba10_bsha_1.TouchPoint.distanceTo(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.fieldHeight, ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.getArgument(), ch.zhaw.ba10_bsha_1.service.MicroGesture.getPoints(), and ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.predictionTolerance.
boolean ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.directionIsDown (double direction) [private]
Definition at line 197 of file MicroGestureDetectionStrategyPrediction.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.analyseMicroGestureDirection().
boolean ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.directionIsLeft (double direction) [private]
Definition at line 207 of file MicroGestureDetectionStrategyPrediction.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.analyseMicroGestureDirection().
boolean ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.directionIsRight (double direction) [private]
Definition at line 202 of file MicroGestureDetectionStrategyPrediction.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.analyseMicroGestureDirection().
boolean ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.directionIsUp (double direction) [private]
Definition at line 192 of file MicroGestureDetectionStrategyPrediction.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.analyseMicroGestureDirection().
String ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.getStrategyDescription () [protected, virtual]
Return a description of the strategy
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 54 of file MicroGestureDetectionStrategyPrediction.java.
String ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.getStrategyName () [protected, virtual]
Return the strategy's name
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 49 of file MicroGestureDetectionStrategyPrediction.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.initialize().
void ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.initialize () [virtual]
Initialize the strategy's StrategyArguments
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 42 of file MicroGestureDetectionStrategyPrediction.java.
References ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.addArgument(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.getStrategyName(), and ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.hasArgument().
Member Data Documentation
float ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.fieldHeight = 0 [private]
Definition at line 32 of file MicroGestureDetectionStrategyPrediction.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.analyseMicroGestureType(), and ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.detectMicroGestures().
boolean ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.mergeMicroGestures = true [private]
Definition at line 33 of file MicroGestureDetectionStrategyPrediction.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.analyseMicroGesture().
float ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.predictionTolerance = 5 [private]
Definition at line 31 of file MicroGestureDetectionStrategyPrediction.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.analyseMicroGestureType(), and ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.detectMicroGestures().
The documentation for this class was generated from the following file:
/media/Daten/Studium/BA/source/BA10-bsha-1/src/ch/zhaw/ba10_bsha_1/strategies/MicroGestureDetectionStrategyPrediction.java