BA10-bsha-1: ch.zhaw.ba10_bsha_1.strategies.PathSmoothingStrategySpline Class Reference
ch.zhaw.ba10_bsha_1.strategies.PathSmoothingStrategySpline Class Reference
Inherits ch::zhaw::ba10_bsha_1::strategies::BaseStrategy, and ch::zhaw::ba10_bsha_1::strategies::IPreprocessingStrategy.
Public Member Functions
void initialize ()
MicroGesture process (MicroGesture micro_gesture)
Protected Member Functions
String getStrategyName ()
String getStrategyDescription ()
Private Member Functions
TouchPoint[] NURBS (TouchPoint[] controlPoints, int nCurvePoints, float[] knot, float[] weight, int size, int d)
double bSplineBlend (int k, int d, double u, float[] knot)
Detailed Description
Implementation of IPreprocessingStrategy that smoothes the path of the given TouchPoints by calculating a spline curve over them and adjusting them accordingly.
Author:
Dominik Giger, Julian Hanhart
Definition at line 17 of file PathSmoothingStrategySpline.java.
Member Function Documentation
double ch.zhaw.ba10_bsha_1.strategies.PathSmoothingStrategySpline.bSplineBlend (int k, int d, double u, float[] knot) [private]
Definition at line 127 of file PathSmoothingStrategySpline.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.PathSmoothingStrategySpline.NURBS().
String ch.zhaw.ba10_bsha_1.strategies.PathSmoothingStrategySpline.getStrategyDescription () [protected, virtual]
Return a description of the strategy
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 34 of file PathSmoothingStrategySpline.java.
String ch.zhaw.ba10_bsha_1.strategies.PathSmoothingStrategySpline.getStrategyName () [protected, virtual]
Return the strategy's name
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 29 of file PathSmoothingStrategySpline.java.
void ch.zhaw.ba10_bsha_1.strategies.PathSmoothingStrategySpline.initialize () [virtual]
Initialize the strategy's StrategyArguments
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 26 of file PathSmoothingStrategySpline.java.
TouchPoint [] ch.zhaw.ba10_bsha_1.strategies.PathSmoothingStrategySpline.NURBS (TouchPoint[] controlPoints, int nCurvePoints, float[] knot, float[] weight, int size, int d) [private]
Definition at line 95 of file PathSmoothingStrategySpline.java.
References ch.zhaw.ba10_bsha_1.strategies.PathSmoothingStrategySpline.bSplineBlend().
Referenced by ch.zhaw.ba10_bsha_1.strategies.PathSmoothingStrategySpline.process().
MicroGesture ch.zhaw.ba10_bsha_1.strategies.PathSmoothingStrategySpline.process (MicroGesture micro_gesture)
Process the TouchPoints of the given MicroGesture
Parameters:
micro_gesture
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.IPreprocessingStrategy.
Definition at line 51 of file PathSmoothingStrategySpline.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.getPoints(), and ch.zhaw.ba10_bsha_1.strategies.PathSmoothingStrategySpline.NURBS().
The documentation for this class was generated from the following file:
/media/Daten/Studium/BA/source/BA10-bsha-1/src/ch/zhaw/ba10_bsha_1/strategies/PathSmoothingStrategySpline.java