BA10-bsha-1: ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCombine Class Reference
ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCombine Class Reference
Inherits ch::zhaw::ba10_bsha_1::strategies::BaseStrategy, and ch::zhaw::ba10_bsha_1::strategies::IMicroGestureDetectionStrategy.
Public Member Functions
void initialize ()
Collection< MicroGesture > detectMicroGestures (Collection< MicroGesture > microGestures)
Protected Member Functions
String getStrategyName ()
String getStrategyDescription ()
Private Member Functions
void setMicroGesture (MicroGesture mg)
Detailed Description
Implementation of IMicroGestureDetectionStrategy which combines MicroGesture with others when needed.
Author:
Dominik Giger, Julian Hanhart
Definition at line 16 of file MicroGestureDetectionStrategyCombine.java.
Member Function Documentation
Collection<MicroGesture> ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCombine.detectMicroGestures (Collection< MicroGesture > microGestures)
Combine MicroGestures when needed
Parameters:
micro_gestures
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.IMicroGestureDetectionStrategy.
Definition at line 49 of file MicroGestureDetectionStrategyCombine.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.addPoint(), ch.zhaw.ba10_bsha_1.service.MicroGesture.getDirection(), ch.zhaw.ba10_bsha_1.service.MicroGesture.getPoints(), ch.zhaw.ba10_bsha_1.service.MicroGesture.getType(), and ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCombine.setMicroGesture().
String ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCombine.getStrategyDescription () [protected, virtual]
Return a description of the strategy
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 32 of file MicroGestureDetectionStrategyCombine.java.
String ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCombine.getStrategyName () [protected, virtual]
Return the strategy's name
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 27 of file MicroGestureDetectionStrategyCombine.java.
void ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCombine.initialize () [virtual]
Initialize the strategy's StrategyArguments
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 24 of file MicroGestureDetectionStrategyCombine.java.
void ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCombine.setMicroGesture (MicroGesture mg) [private]
Definition at line 83 of file MicroGestureDetectionStrategyCombine.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.getPoints(), and ch.zhaw.ba10_bsha_1.service.MicroGesture.setType().
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCombine.detectMicroGestures().
The documentation for this class was generated from the following file:
/media/Daten/Studium/BA/source/BA10-bsha-1/src/ch/zhaw/ba10_bsha_1/strategies/MicroGestureDetectionStrategyCombine.java