BA10-bsha-1: ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyGraph Class Reference
ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyGraph Class Reference
Inherits ch::zhaw::ba10_bsha_1::strategies::BaseStrategy, and ch::zhaw::ba10_bsha_1::strategies::ICharacterDetectionStrategy.
Public Member Functions
CharacterDetectionStrategyGraph ()
Collection< Character > detectCharacter (Collection< MicroGesture > micro_gestures)
Protected Member Functions
void initArguments ()
String getStrategyName ()
String getStrategyDescription ()
Private Attributes
Node root
Detailed Description
Implementation of ICharacterDetectionStrategy using a graph created by an IGraphFactory.
Author:
Julian Hanhart, Dominik Giger
Definition at line 20 of file CharacterDetectionStrategyGraph.java.
Constructor & Destructor Documentation
ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyGraph.CharacterDetectionStrategyGraph ()
Definition at line 36 of file CharacterDetectionStrategyGraph.java.
References ch.zhaw.ba10_bsha_1.graph.IGraphFactory.createRoot(), ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.getArgument(), and ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyGraph.root.
Member Function Documentation
Collection<Character> ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyGraph.detectCharacter (Collection< MicroGesture > micro_gestures)
Detect Characters out of the given MicroGestures
Parameters:
micro_gestures
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.ICharacterDetectionStrategy.
Definition at line 77 of file CharacterDetectionStrategyGraph.java.
References ch.zhaw.ba10_bsha_1.graph.Node.consume(), and ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyGraph.root.
String ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyGraph.getStrategyDescription () [protected, virtual]
Return a description of the strategy
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 60 of file CharacterDetectionStrategyGraph.java.
String ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyGraph.getStrategyName () [protected, virtual]
Return the strategy's name
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 55 of file CharacterDetectionStrategyGraph.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyGraph.initArguments().
void ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyGraph.initArguments () [protected, virtual]
Initialize the strategy's StrategyArguments
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 50 of file CharacterDetectionStrategyGraph.java.
References ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.addArgument(), and ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyGraph.getStrategyName().
Member Data Documentation
Node ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyGraph.root [private]
Definition at line 28 of file CharacterDetectionStrategyGraph.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyGraph.CharacterDetectionStrategyGraph(), and ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyGraph.detectCharacter().
The documentation for this class was generated from the following file:
/media/Daten/Studium/BA/source/BA10-bsha-1/src/ch/zhaw/ba10_bsha_1/strategies/CharacterDetectionStrategyGraph.java