BA10-bsha-1: ch.zhaw.ba10_bsha_1.strategies.BaseStrategy Class Reference
ch.zhaw.ba10_bsha_1.strategies.BaseStrategy Class Reference
Inherits ch::zhaw::ba10_bsha_1::strategies::IStrategy.
Inherited by ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyDummyGraph, ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyGraph, ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyNone, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCircles, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCombine, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyEdges, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyNone, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyRemoveTiny, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategySmoothing, ch.zhaw.ba10_bsha_1.strategies.PathSmoothingStrategyAverage, ch.zhaw.ba10_bsha_1.strategies.PathSmoothingStrategySpline, ch.zhaw.ba10_bsha_1.strategies.PostprocessingStrategyLog, ch.zhaw.ba10_bsha_1.strategies.PostprocessingStrategyNone, ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog, ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyNone, and ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyNormalizePoints.
Public Member Functions
BaseStrategy ()
abstract void initialize ()
String toString ()
String getDescription ()
boolean isEnabled ()
void setEnabled (boolean enable)
boolean hasArgument (String name)
StrategyArgument getArgument (String name)
void setArgument (StrategyArgument arg)
void addArgument (StrategyArgument arg)
Collection< StrategyArgument > getConfiguration ()
Protected Member Functions
abstract String getStrategyName ()
abstract String getStrategyDescription ()
Protected Attributes
boolean enabled
Private Attributes
Hashtable< String,
StrategyArgument > arguments
Detailed Description
Abstract Base Class for strategies. Takes care of the management of the strategy's arguments. Derived classes need to implement the methods used to initialize its arguments and its name and description getters.
See also:
ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyNormalizePoints
ch.zhaw.ba10_bsha_1.strategies.PathSmoothingStrategyAverage
ch.zhaw.ba10_bsha_1.strategies.PathSmoothingStrategySpline
ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyNone
ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyRemoveTiny
ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCombine
ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction
ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature
ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyEdges
ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCircles
ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle
ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyNone
ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyDummyGraph
ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyGraph
ch.zhaw.ba10_bsha_1.strategies.PostprocessingStrategyNone
Author:
Julian Hanhart, Domink Giger
Definition at line 34 of file BaseStrategy.java.
Constructor & Destructor Documentation
ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.BaseStrategy ()
Definition at line 51 of file BaseStrategy.java.
References ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.arguments, ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.enabled, and ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.initialize().
Member Function Documentation
void ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.addArgument (StrategyArgument arg)
Implements ch.zhaw.ba10_bsha_1.strategies.IStrategy.
Definition at line 131 of file BaseStrategy.java.
References ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.arguments, and ch.zhaw.ba10_bsha_1.StrategyArgument.getArgumentName().
Referenced by ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog.initialize(), ch.zhaw.ba10_bsha_1.strategies.PostprocessingStrategyLog.initialize(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.initialize(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog.initialize(), and ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyGraph.initialize().
StrategyArgument ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.getArgument (String name)
Implements ch.zhaw.ba10_bsha_1.strategies.IStrategy.
Definition at line 115 of file BaseStrategy.java.
References ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.arguments.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.detectMicroGestures(), ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog.initialize(), ch.zhaw.ba10_bsha_1.strategies.PostprocessingStrategyLog.initialize(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog.initialize(), and ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyGraph.initialize().
Collection<StrategyArgument> ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.getConfiguration ()
Returns a Collection of all the strategy's StrategyArguments
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.IStrategy.
Definition at line 143 of file BaseStrategy.java.
References ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.arguments, ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.enabled, and ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.getStrategyName().
String ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.getDescription ()
Implements ch.zhaw.ba10_bsha_1.strategies.IStrategy.
Definition at line 95 of file BaseStrategy.java.
References ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.getStrategyDescription().
abstract String ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.getStrategyDescription () [protected, pure virtual]
Return a description of the strategy
Returns:
Implemented in ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyDummyGraph, ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyGraph, ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyNone, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCircles, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCombine, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyEdges, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyNone, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyRemoveTiny, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategySmoothing, ch.zhaw.ba10_bsha_1.strategies.PathSmoothingStrategyAverage, ch.zhaw.ba10_bsha_1.strategies.PathSmoothingStrategySpline, ch.zhaw.ba10_bsha_1.strategies.PostprocessingStrategyLog, ch.zhaw.ba10_bsha_1.strategies.PostprocessingStrategyNone, ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog, ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyNone, and ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyNormalizePoints.
Referenced by ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.getDescription().
abstract String ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.getStrategyName () [protected, pure virtual]
Return the strategy's name
Returns:
Implemented in ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyDummyGraph, ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyGraph, ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyNone, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCircles, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCombine, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyEdges, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyNone, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyRemoveTiny, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategySmoothing, ch.zhaw.ba10_bsha_1.strategies.PathSmoothingStrategyAverage, ch.zhaw.ba10_bsha_1.strategies.PathSmoothingStrategySpline, ch.zhaw.ba10_bsha_1.strategies.PostprocessingStrategyLog, ch.zhaw.ba10_bsha_1.strategies.PostprocessingStrategyNone, ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog, ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyNone, and ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyNormalizePoints.
Referenced by ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.getConfiguration(), ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.setArgument(), and ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.toString().
boolean ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.hasArgument (String name)
Implements ch.zhaw.ba10_bsha_1.strategies.IStrategy.
Definition at line 110 of file BaseStrategy.java.
References ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.arguments.
Referenced by ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog.initialize(), ch.zhaw.ba10_bsha_1.strategies.PostprocessingStrategyLog.initialize(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction.initialize(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog.initialize(), and ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyGraph.initialize().
abstract void ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.initialize () [pure virtual]
Initialize the strategy's StrategyArguments
Implements ch.zhaw.ba10_bsha_1.strategies.IStrategy.
Implemented in ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyDummyGraph, ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyGraph, ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyNone, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCircles, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCombine, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyEdges, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyNone, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyRemoveTiny, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategySmoothing, ch.zhaw.ba10_bsha_1.strategies.PathSmoothingStrategyAverage, ch.zhaw.ba10_bsha_1.strategies.PathSmoothingStrategySpline, ch.zhaw.ba10_bsha_1.strategies.PostprocessingStrategyLog, ch.zhaw.ba10_bsha_1.strategies.PostprocessingStrategyNone, ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog, ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyNone, and ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyNormalizePoints.
Referenced by ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.BaseStrategy().
boolean ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.isEnabled ()
Implements ch.zhaw.ba10_bsha_1.strategies.IStrategy.
Definition at line 100 of file BaseStrategy.java.
References ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.enabled.
void ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.setArgument (StrategyArgument arg)
Implements ch.zhaw.ba10_bsha_1.strategies.IStrategy.
Definition at line 120 of file BaseStrategy.java.
References ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.arguments, ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.enabled, ch.zhaw.ba10_bsha_1.StrategyArgument.getArgumentName(), ch.zhaw.ba10_bsha_1.StrategyArgument.getArgumentValue(), ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.getStrategyName(), and ch.zhaw.ba10_bsha_1.StrategyArgument.getStrategyName().
void ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.setEnabled (boolean enable)
Implements ch.zhaw.ba10_bsha_1.strategies.IStrategy.
Definition at line 105 of file BaseStrategy.java.
References ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.enabled.
String ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.toString ()
Implements ch.zhaw.ba10_bsha_1.strategies.IStrategy.
Definition at line 90 of file BaseStrategy.java.
References ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.getStrategyName().
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog.detectMicroGestures(), ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog.process(), and ch.zhaw.ba10_bsha_1.strategies.PostprocessingStrategyLog.process().
Member Data Documentation
Hashtable<String, StrategyArgument> ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.arguments [private]
Definition at line 42 of file BaseStrategy.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.addArgument(), ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.BaseStrategy(), ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.getArgument(), ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.getConfiguration(), ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.hasArgument(), and ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.setArgument().
boolean ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.enabled [protected]
Definition at line 43 of file BaseStrategy.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.BaseStrategy(), ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.getConfiguration(), ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.isEnabled(), ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.setArgument(), and ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.setEnabled().
The documentation for this class was generated from the following file:
/media/Daten/Studium/BA/source/BA10-bsha-1/src/ch/zhaw/ba10_bsha_1/strategies/BaseStrategy.java