BA10-bsha-1: ch.zhaw.ba10_bsha_1.graph.GraphMLExport Class Reference
ch.zhaw.ba10_bsha_1.graph.GraphMLExport Class Reference
Public Member Functions
void writeFile (Node graph, File file) throws IOException
Private Member Functions
void writeNode (Node n, PrintWriter stream) throws IOException
void writeEdge (Edge e, PrintWriter stream) throws IOException
Private Attributes
ArrayList< Edge > edges
ArrayList< Node > nodes
Static Private Attributes
static String footer = "</graph>\n</graphml>"
static String header
Detailed Description
Export graph to GraphML file.
Author:
Dominik Giger, Julian Hanhart
Definition at line 15 of file GraphMLExport.java.
Member Function Documentation
void ch.zhaw.ba10_bsha_1.graph.GraphMLExport.writeEdge (Edge e, PrintWriter stream) throws IOException [private]
Definition at line 85 of file GraphMLExport.java.
References ch.zhaw.ba10_bsha_1.graph.GraphMLExport.edges, and ch.zhaw.ba10_bsha_1.graph.GraphMLExport.writeNode().
Referenced by ch.zhaw.ba10_bsha_1.graph.GraphMLExport.writeNode().
void ch.zhaw.ba10_bsha_1.graph.GraphMLExport.writeFile (Node graph, File file) throws IOException
Definition at line 46 of file GraphMLExport.java.
References ch.zhaw.ba10_bsha_1.graph.GraphMLExport.edges, ch.zhaw.ba10_bsha_1.graph.GraphMLExport.footer, ch.zhaw.ba10_bsha_1.graph.GraphMLExport.header, ch.zhaw.ba10_bsha_1.graph.GraphMLExport.nodes, and ch.zhaw.ba10_bsha_1.graph.GraphMLExport.writeNode().
void ch.zhaw.ba10_bsha_1.graph.GraphMLExport.writeNode (Node n, PrintWriter stream) throws IOException [private]
Definition at line 68 of file GraphMLExport.java.
References ch.zhaw.ba10_bsha_1.graph.GraphMLExport.nodes, and ch.zhaw.ba10_bsha_1.graph.GraphMLExport.writeEdge().
Referenced by ch.zhaw.ba10_bsha_1.graph.GraphMLExport.writeEdge(), and ch.zhaw.ba10_bsha_1.graph.GraphMLExport.writeFile().
Member Data Documentation
ArrayList<Edge> ch.zhaw.ba10_bsha_1.graph.GraphMLExport.edges [private]
Definition at line 37 of file GraphMLExport.java.
Referenced by ch.zhaw.ba10_bsha_1.graph.GraphMLExport.writeEdge(), and ch.zhaw.ba10_bsha_1.graph.GraphMLExport.writeFile().
String ch.zhaw.ba10_bsha_1.graph.GraphMLExport.footer = "</graph>\n</graphml>" [static, private]
Definition at line 23 of file GraphMLExport.java.
Referenced by ch.zhaw.ba10_bsha_1.graph.GraphMLExport.writeFile().
String ch.zhaw.ba10_bsha_1.graph.GraphMLExport.header [static, private]
Initial value:
 "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<graphml xmlns=\"http://graphml.graphdrawing.org/xmlns\"\n" +
                "\txmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n" +
                "\txsi:schemaLcation=\"http://graphml.graphdrawing.org/xmlns\n" +
                "\t http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd\">\n" +
                "\t<key id=\"d0\" for=\"node\" attr.name=\"character\" attr.type=\"string\">\n" +
                "\t\t<default></default>\n" +
                "\t</key>\n" +
                "\t<key id=\"d1\" for=\"node\" attr.name=\"test\" attr.type=\"string\">\n" +
                "\t\t<default></default>\n" +
                "\t</key>\n" +
                "<graph id=\"G\" edgedefault=\"directed\">\n"
Definition at line 24 of file GraphMLExport.java.
Referenced by ch.zhaw.ba10_bsha_1.graph.GraphMLExport.writeFile().
ArrayList<Node> ch.zhaw.ba10_bsha_1.graph.GraphMLExport.nodes [private]
Definition at line 38 of file GraphMLExport.java.
Referenced by ch.zhaw.ba10_bsha_1.graph.GraphMLExport.writeFile(), and ch.zhaw.ba10_bsha_1.graph.GraphMLExport.writeNode().
The documentation for this class was generated from the following file:
/media/Daten/Studium/BA/source/BA10-bsha-1/src/ch/zhaw/ba10_bsha_1/graph/GraphMLExport.java