BA10-bsha-1: ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle Class Reference
ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle Class Reference
Inherits ch::zhaw::ba10_bsha_1::strategies::BaseStrategy, and ch::zhaw::ba10_bsha_1::strategies::IMicroGestureDetectionStrategy.
Public Member Functions
Collection< MicroGesture > detectMicroGestures (Collection< MicroGesture > microGestures)
Protected Member Functions
void initArguments ()
String getStrategyName ()
String getStrategyDescription ()
Private Member Functions
void setMicroGesture (MicroGesture mg)
double calculateDistance (TouchPoint a, double m1, double q1)
float analyseMicroGestureDirection (MicroGesture mg)
Detailed Description
Implementation of IMicroGestureDetectionStrategy which detects half circles in the given MicroGestures.
Author:
Dominik Giger, Julian Hanhart
Definition at line 19 of file MicroGestureDetectionStrategyHalfCircle.java.
Member Function Documentation
float ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle.analyseMicroGestureDirection (MicroGesture mg) [private]
Definition at line 227 of file MicroGestureDetectionStrategyHalfCircle.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.getPoints(), ch.zhaw.ba10_bsha_1.service.MicroGesture.getType(), and ch.zhaw.ba10_bsha_1.service.MicroGesture.setDirection2().
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle.detectMicroGestures().
double ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle.calculateDistance (TouchPoint a, double m1, double q1) [private]
Definition at line 210 of file MicroGestureDetectionStrategyHalfCircle.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle.setMicroGesture().
Collection<MicroGesture> ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle.detectMicroGestures (Collection< MicroGesture > microGestures)
Detect half circles in the TouchPoints of the given MicroGestures
Parameters:
micro_gestures
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.IMicroGestureDetectionStrategy.
Definition at line 52 of file MicroGestureDetectionStrategyHalfCircle.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.addPoint(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle.analyseMicroGestureDirection(), ch.zhaw.ba10_bsha_1.service.MicroGesture.setDirection(), and ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle.setMicroGesture().
String ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle.getStrategyDescription () [protected, virtual]
Return a description of the strategy
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 35 of file MicroGestureDetectionStrategyHalfCircle.java.
String ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle.getStrategyName () [protected, virtual]
Return the strategy's name
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 30 of file MicroGestureDetectionStrategyHalfCircle.java.
void ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle.initArguments () [protected, virtual]
Initialize the strategy's StrategyArguments
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 27 of file MicroGestureDetectionStrategyHalfCircle.java.
void ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle.setMicroGesture (MicroGesture mg) [private]
Definition at line 168 of file MicroGestureDetectionStrategyHalfCircle.java.
References ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle.calculateDistance(), ch.zhaw.ba10_bsha_1.service.MicroGesture.getPoints(), and ch.zhaw.ba10_bsha_1.service.MicroGesture.setType().
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle.detectMicroGestures().
The documentation for this class was generated from the following file:
/media/Daten/Studium/BA/source/BA10-bsha-1/src/ch/zhaw/ba10_bsha_1/strategies/MicroGestureDetectionStrategyHalfCircle.java