BA10-bsha-1: ch.zhaw.ba10_bsha_1.strategies.StrategyManager< Strategy extends IStrategy > Class Reference
ch.zhaw.ba10_bsha_1.strategies.StrategyManager< Strategy extends IStrategy > Class Reference
Public Member Functions
Strategy getStrategy (String name)
String[] getStrategyList ()
void addStrategy (Strategy strategy)
void addStrategies (Collection< Strategy > strategies)
void remStrategy (Strategy strategy)
void remStrategies (Collection< Strategy > strategies)
StrategyArgument getArgument (StrategyArgument arg)
void setArgument (StrategyArgument arg)
void broadcastArgument (StrategyArgument arg)
Protected Member Functions
StrategyManager ()
abstract void initManager ()
Private Attributes
Hashtable< String, Strategy > strategies
Detailed Description
Abstract Base Class for a class managing objects implementing IStrategy.
See also:
ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyManager
ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyManager
ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyManager
ch.zhaw.ba10_bsha_1.strategies.PostprocessingStrategyManager
Author:
Julian Hanhart, Dominik Giger
Parameters:
<Strategy>
Definition at line 21 of file StrategyManager.java.
Constructor & Destructor Documentation
ch.zhaw.ba10_bsha_1.strategies.StrategyManager< Strategy extends IStrategy >.StrategyManager () [protected]
Definition at line 37 of file StrategyManager.java.
Member Function Documentation
void ch.zhaw.ba10_bsha_1.strategies.StrategyManager< Strategy extends IStrategy >.addStrategies (Collection< Strategy > strategies)
Definition at line 78 of file StrategyManager.java.
void ch.zhaw.ba10_bsha_1.strategies.StrategyManager< Strategy extends IStrategy >.addStrategy (Strategy strategy)
Definition at line 72 of file StrategyManager.java.
void ch.zhaw.ba10_bsha_1.strategies.StrategyManager< Strategy extends IStrategy >.broadcastArgument (StrategyArgument arg)
Broadcast StrategyArgument to all strategies that use the given argument
Parameters:
arg
Definition at line 124 of file StrategyManager.java.
References ch.zhaw.ba10_bsha_1.StrategyArgument.getArgumentName(), and ch.zhaw.ba10_bsha_1.StrategyArgument.setStrategyName().
StrategyArgument ch.zhaw.ba10_bsha_1.strategies.StrategyManager< Strategy extends IStrategy >.getArgument (StrategyArgument arg)
Get the argument specified in the given StrategyArgument from the Strategy it specifies
Parameters:
arg
Returns:
Definition at line 106 of file StrategyManager.java.
References ch.zhaw.ba10_bsha_1.StrategyArgument.getArgumentName(), and ch.zhaw.ba10_bsha_1.StrategyArgument.getStrategyName().
Strategy ch.zhaw.ba10_bsha_1.strategies.StrategyManager< Strategy extends IStrategy >.getStrategy (String name)
Definition at line 59 of file StrategyManager.java.
String [] ch.zhaw.ba10_bsha_1.strategies.StrategyManager< Strategy extends IStrategy >.getStrategyList ()
Definition at line 67 of file StrategyManager.java.
abstract void ch.zhaw.ba10_bsha_1.strategies.StrategyManager< Strategy extends IStrategy >.initManager () [protected, pure virtual]
Initialize and add the Strategies it should manage to the manager
void ch.zhaw.ba10_bsha_1.strategies.StrategyManager< Strategy extends IStrategy >.remStrategies (Collection< Strategy > strategies)
Definition at line 88 of file StrategyManager.java.
void ch.zhaw.ba10_bsha_1.strategies.StrategyManager< Strategy extends IStrategy >.remStrategy (Strategy strategy)
Definition at line 84 of file StrategyManager.java.
void ch.zhaw.ba10_bsha_1.strategies.StrategyManager< Strategy extends IStrategy >.setArgument (StrategyArgument arg)
Set the argument specified in the given StrategyArgument at the Strategy it specifies
Parameters:
arg
Definition at line 115 of file StrategyManager.java.
References ch.zhaw.ba10_bsha_1.StrategyArgument.getStrategyName().
Member Data Documentation
Hashtable<String, Strategy> ch.zhaw.ba10_bsha_1.strategies.StrategyManager< Strategy extends IStrategy >.strategies [private]
Definition at line 29 of file StrategyManager.java.
The documentation for this class was generated from the following file:
/media/Daten/Studium/BA/source/BA10-bsha-1/src/ch/zhaw/ba10_bsha_1/strategies/StrategyManager.java