BA10-bsha-1: ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog Class Reference
ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog Class Reference
Inherits ch::zhaw::ba10_bsha_1::strategies::BaseStrategy, and ch::zhaw::ba10_bsha_1::strategies::IMicroGestureDetectionStrategy.
Public Member Functions
void initialize ()
Collection< MicroGesture > detectMicroGestures (Collection< MicroGesture > micro_gestures)
Protected Member Functions
String getStrategyName ()
String getStrategyDescription ()
Private Attributes
File logFile
Static Private Attributes
static final String TAG = "MGDS_Log"
Detailed Description
Example of an implementation of IMicroGestureDetectionStrategy which logs the given MicroGestures to Logcat and into a log-file and returns them unchanged
Author:
Julian Hanhart, Dominik Giger
Definition at line 25 of file MicroGestureDetectionStrategyLog.java.
Member Function Documentation
Collection<MicroGesture> ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog.detectMicroGestures (Collection< MicroGesture > micro_gestures)
Logs the given MicroGestures to Logcat and into a file and returns the unchanged
Parameters:
micro_gestures
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.IMicroGestureDetectionStrategy.
Definition at line 80 of file MicroGestureDetectionStrategyLog.java.
References ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog.logFile, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog.TAG, and ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.toString().
String ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog.getStrategyDescription () [protected, virtual]
Return a description of the strategy
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 63 of file MicroGestureDetectionStrategyLog.java.
String ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog.getStrategyName () [protected, virtual]
Return the strategy's name
Returns:
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 58 of file MicroGestureDetectionStrategyLog.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog.initialize().
void ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog.initialize () [virtual]
Initialize the strategy's StrategyArguments
Implements ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Definition at line 43 of file MicroGestureDetectionStrategyLog.java.
References ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.addArgument(), ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.getArgument(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog.getStrategyName(), ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.hasArgument(), ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog.logFile, and ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog.TAG.
Member Data Documentation
File ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog.logFile [private]
Definition at line 34 of file MicroGestureDetectionStrategyLog.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog.detectMicroGestures(), and ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog.initialize().
final String ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog.TAG = "MGDS_Log" [static, private]
Definition at line 33 of file MicroGestureDetectionStrategyLog.java.
Referenced by ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog.detectMicroGestures(), and ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog.initialize().
The documentation for this class was generated from the following file:
/media/Daten/Studium/BA/source/BA10-bsha-1/src/ch/zhaw/ba10_bsha_1/strategies/MicroGestureDetectionStrategyLog.java