BA10-bsha-1: ch.zhaw.ba10_bsha_1.service.MicroGestureTester Class Reference
ch.zhaw.ba10_bsha_1.service.MicroGestureTester Class Reference
Public Member Functions
MicroGestureTester (int type, char dir_pattern)
MicroGestureTester (String init)
boolean validate (MicroGesture micro_gesture)
Static Public Member Functions
static char StrToPattern (String str)
Static Public Attributes
static final char MASK_DIRECTION_LEFT = 1
static final char MASK_DIRECTION_RIGHT = 1 << 1
static final char MASK_DIRECTION_UP = 1 << 2
static final char MASK_DIRECTION_DOWN = 1 << 3
static final char MASK_DIRECTION_SWITCH = 1 << 4
Private Attributes
int type
char directionPattern
Detailed Description
Represents a test-case one can validate a MicroGesture against.
Author:
Julian Hanhart, Dominik Giger
Definition at line 9 of file MicroGestureTester.java.
Constructor & Destructor Documentation
ch.zhaw.ba10_bsha_1.service.MicroGestureTester.MicroGestureTester (int type, char dir_pattern)
Definition at line 32 of file MicroGestureTester.java.
References ch.zhaw.ba10_bsha_1.service.MicroGestureTester.directionPattern.
ch.zhaw.ba10_bsha_1.service.MicroGestureTester.MicroGestureTester (String init)
Definition at line 37 of file MicroGestureTester.java.
References ch.zhaw.ba10_bsha_1.service.MicroGestureTester.directionPattern, ch.zhaw.ba10_bsha_1.service.MicroGestureTester.StrToPattern(), and ch.zhaw.ba10_bsha_1.service.MicroGestureTester.type.
Member Function Documentation
static char ch.zhaw.ba10_bsha_1.service.MicroGestureTester.StrToPattern (String str) [static]
Translate a given String-representation of a tester to its char pattern
Parameters:
str
Definition at line 78 of file MicroGestureTester.java.
References ch.zhaw.ba10_bsha_1.service.MicroGestureTester.MASK_DIRECTION_DOWN, ch.zhaw.ba10_bsha_1.service.MicroGestureTester.MASK_DIRECTION_LEFT, ch.zhaw.ba10_bsha_1.service.MicroGestureTester.MASK_DIRECTION_RIGHT, ch.zhaw.ba10_bsha_1.service.MicroGestureTester.MASK_DIRECTION_SWITCH, and ch.zhaw.ba10_bsha_1.service.MicroGestureTester.MASK_DIRECTION_UP.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGestureTester.MicroGestureTester().
boolean ch.zhaw.ba10_bsha_1.service.MicroGestureTester.validate (MicroGesture micro_gesture)
Validate the given MicroGesture against the tester
Parameters:
micro_gesture
Definition at line 56 of file MicroGestureTester.java.
References ch.zhaw.ba10_bsha_1.service.MicroGesture.directionHasSwitched(), ch.zhaw.ba10_bsha_1.service.MicroGesture.directionIsDown(), ch.zhaw.ba10_bsha_1.service.MicroGesture.directionIsLeft(), ch.zhaw.ba10_bsha_1.service.MicroGesture.directionIsRight(), ch.zhaw.ba10_bsha_1.service.MicroGesture.directionIsUp(), ch.zhaw.ba10_bsha_1.service.MicroGestureTester.directionPattern, ch.zhaw.ba10_bsha_1.service.MicroGesture.getType(), ch.zhaw.ba10_bsha_1.service.MicroGestureTester.MASK_DIRECTION_DOWN, ch.zhaw.ba10_bsha_1.service.MicroGestureTester.MASK_DIRECTION_LEFT, ch.zhaw.ba10_bsha_1.service.MicroGestureTester.MASK_DIRECTION_RIGHT, ch.zhaw.ba10_bsha_1.service.MicroGestureTester.MASK_DIRECTION_SWITCH, ch.zhaw.ba10_bsha_1.service.MicroGestureTester.MASK_DIRECTION_UP, and ch.zhaw.ba10_bsha_1.service.MicroGestureTester.type.
Referenced by ch.zhaw.ba10_bsha_1.graph.Node.consume().
Member Data Documentation
char ch.zhaw.ba10_bsha_1.service.MicroGestureTester.directionPattern [private]
Definition at line 24 of file MicroGestureTester.java.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGestureTester.MicroGestureTester(), and ch.zhaw.ba10_bsha_1.service.MicroGestureTester.validate().
final char ch.zhaw.ba10_bsha_1.service.MicroGestureTester.MASK_DIRECTION_DOWN = 1 << 3 [static]
Definition at line 20 of file MicroGestureTester.java.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGestureTester.StrToPattern(), and ch.zhaw.ba10_bsha_1.service.MicroGestureTester.validate().
final char ch.zhaw.ba10_bsha_1.service.MicroGestureTester.MASK_DIRECTION_LEFT = 1 [static]
Definition at line 17 of file MicroGestureTester.java.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGestureTester.StrToPattern(), and ch.zhaw.ba10_bsha_1.service.MicroGestureTester.validate().
final char ch.zhaw.ba10_bsha_1.service.MicroGestureTester.MASK_DIRECTION_RIGHT = 1 << 1 [static]
Definition at line 18 of file MicroGestureTester.java.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGestureTester.StrToPattern(), and ch.zhaw.ba10_bsha_1.service.MicroGestureTester.validate().
final char ch.zhaw.ba10_bsha_1.service.MicroGestureTester.MASK_DIRECTION_SWITCH = 1 << 4 [static]
Definition at line 21 of file MicroGestureTester.java.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGestureTester.StrToPattern(), and ch.zhaw.ba10_bsha_1.service.MicroGestureTester.validate().
final char ch.zhaw.ba10_bsha_1.service.MicroGestureTester.MASK_DIRECTION_UP = 1 << 2 [static]
Definition at line 19 of file MicroGestureTester.java.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGestureTester.StrToPattern(), and ch.zhaw.ba10_bsha_1.service.MicroGestureTester.validate().
int ch.zhaw.ba10_bsha_1.service.MicroGestureTester.type [private]
Definition at line 23 of file MicroGestureTester.java.
Referenced by ch.zhaw.ba10_bsha_1.service.MicroGestureTester.MicroGestureTester(), and ch.zhaw.ba10_bsha_1.service.MicroGestureTester.validate().
The documentation for this class was generated from the following file:
/media/Daten/Studium/BA/source/BA10-bsha-1/src/ch/zhaw/ba10_bsha_1/service/MicroGestureTester.java