BA10-bsha-1: ch.zhaw.ba10_bsha_1.strategies.IStrategy Interface Reference
ch.zhaw.ba10_bsha_1.strategies.IStrategy Interface Reference
Inherited by ch.zhaw.ba10_bsha_1.strategies.BaseStrategy, ch.zhaw.ba10_bsha_1.strategies.ICharacterDetectionStrategy, ch.zhaw.ba10_bsha_1.strategies.IMicroGestureDetectionStrategy, ch.zhaw.ba10_bsha_1.strategies.IPostprocessingStrategy, and ch.zhaw.ba10_bsha_1.strategies.IPreprocessingStrategy.
Public Member Functions
void initialize ()
String toString ()
String getDescription ()
boolean isEnabled ()
void setEnabled (boolean enable)
boolean hasArgument (String name)
StrategyArgument getArgument (String name)
void setArgument (StrategyArgument arg)
void addArgument (StrategyArgument arg)
Collection< StrategyArgument > getConfiguration ()
Detailed Description
Interface defining a strategy. Note that the actual type of a strategy and its processing method are described through a series of additional interfaces derived from this one, since their processing methods take different types of arguments and because they have different return types.
See also:
ch.zhaw.ba10_bsha_1.strategies.IPreprocessingStrategy
ch.zhaw.ba10_bsha_1.strategies.IMicroGestureDetectionStrategy
ch.zhaw.ba10_bsha_1.strategies.ICharacterDetectionStrategy
ch.zhaw.ba10_bsha_1.strategies.IPostprocessingStrategy
Author:
Julian Hanhart, Dominik Giger
Definition at line 21 of file IStrategy.java.
Member Function Documentation
void ch.zhaw.ba10_bsha_1.strategies.IStrategy.addArgument (StrategyArgument arg)
Implemented in ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
StrategyArgument ch.zhaw.ba10_bsha_1.strategies.IStrategy.getArgument (String name)
Implemented in ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Collection<StrategyArgument> ch.zhaw.ba10_bsha_1.strategies.IStrategy.getConfiguration ()
Implemented in ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
String ch.zhaw.ba10_bsha_1.strategies.IStrategy.getDescription ()
Implemented in ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Referenced by ch.zhaw.ba10_bsha_1.service.DetectionService.printStrategy().
boolean ch.zhaw.ba10_bsha_1.strategies.IStrategy.hasArgument (String name)
Implemented in ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
void ch.zhaw.ba10_bsha_1.strategies.IStrategy.initialize ()
Implemented in ch.zhaw.ba10_bsha_1.strategies.BaseStrategy, ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyDummyGraph, ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyGraph, ch.zhaw.ba10_bsha_1.strategies.CharacterDetectionStrategyNone, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCircles, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCombine, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyCurvature, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyEdges, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyHalfCircle, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLines, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyLog, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyNone, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyPrediction, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategyRemoveTiny, ch.zhaw.ba10_bsha_1.strategies.MicroGestureDetectionStrategySmoothing, ch.zhaw.ba10_bsha_1.strategies.PathSmoothingStrategyAverage, ch.zhaw.ba10_bsha_1.strategies.PathSmoothingStrategySpline, ch.zhaw.ba10_bsha_1.strategies.PostprocessingStrategyLog, ch.zhaw.ba10_bsha_1.strategies.PostprocessingStrategyNone, ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyLog, ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyNone, and ch.zhaw.ba10_bsha_1.strategies.PreprocessingStrategyNormalizePoints.
boolean ch.zhaw.ba10_bsha_1.strategies.IStrategy.isEnabled ()
Implemented in ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Referenced by ch.zhaw.ba10_bsha_1.service.DetectionService.printStrategy(), and ch.zhaw.ba10_bsha_1.service.DetectionService.startDetection().
void ch.zhaw.ba10_bsha_1.strategies.IStrategy.setArgument (StrategyArgument arg)
Implemented in ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
void ch.zhaw.ba10_bsha_1.strategies.IStrategy.setEnabled (boolean enable)
Implemented in ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
String ch.zhaw.ba10_bsha_1.strategies.IStrategy.toString ()
Implemented in ch.zhaw.ba10_bsha_1.strategies.BaseStrategy.
Referenced by ch.zhaw.ba10_bsha_1.service.DetectionService.printStrategy().
The documentation for this interface was generated from the following file:
/media/Daten/Studium/BA/source/BA10-bsha-1/src/ch/zhaw/ba10_bsha_1/strategies/IStrategy.java